.github/workflows/python-test.yaml
- upgrading actions/checkout to v4
- split unit task into different CUDA devices
- add timeout config
=> [CI/CD] Upgrading actions/checkout to v4

.github/workflows/python-test.yaml, README.md, README_cn.md, benchmark/test_pointwise_perf.py, src/flag_gems/ops/dropout.py, src/flag_gems/ops/layernorm.py, src/flag_gems/utils/pointwise_dynamic.py, tests/test_binary_pointwise_ops.py, tests/test_unary_pointwise_ops.py
merge master code into cambricon and fix some error
=> Cambricon merge 0611

src/flag_gems/ops/argmax.py, src/flag_gems/ops/max.py, src/flag_gems/ops/min.py
Add some configuration to ensure a working kernel
=> cambricon: add config of autotune to argmax, max and min

benchmark/conftest.py, benchmark/performance_utils.py
=> cambricon: add perf test adopt

CONTRIBUTING.md, tests/test_special_ops.py
Add pre-commit in CONTRIBUTING.md
=> Add pre-commit in CONTRIBUTING.md

src/flag_gems/utils/pointwise_dynamic.py, tests/run_all_tests.sh
=> cambricon: fix num warps

src/flag_gems/ops/log_softmax.py, tests/test_reduction_ops.py
add split c kernel for log softmax forward and backward to avoid nram error
=> cambricon: fix log softmax nram

src/flag_gems/ops/softmax.py, tests/test_reduction_ops.py
add softmax forward/backward kernel with c split
=> cambricon: fix softmax nram error

src/flag_gems/ops/cumsum.py, tests/accuracy_utils.py, tests/test_reduction_ops.py
fix cumsum nram error, add split kernel
=> cambricon: fix cumsum nram error

src/flag_gems/ops/dropout.py, src/flag_gems/ops/softmax.py, src/flag_gems/ops/vector_norm.py, tests/test_libentry.py, tests/test_pointwise_type_promotion.py
=> cambricon: fix errors in merge code 0708

benchmark/test_pointwise_perf.py, src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/isclose.py, tests/accuracy_utils.py, tests/test_binary_pointwise_ops.py
1. Add isclose and allclose op.
2. Add unit tests and performance tests of these two ops.
=> [Operator] Add isclose & allclose op

tests/test_binary_pointwise_ops.py
1. Fix tol accuracy of isclose op test
=> [Operator] Fix tol accuracy of isclose op test

benchmark/test_pointwise_perf.py, src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/isfinite.py, tests/test_unary_pointwise_ops.py
1. Add isfinite op as a pointwise op.
2. Add unit tests and performance tests of this op.
=> [Operator] Add isfinite op

README.md, README_cn.md, examples/model_llava_test.py, src/flag_gems/ops/cumsum.py, src/flag_gems/ops/eq.py, src/flag_gems/ops/sum.py
Considering 2 special cases and fix bugs: 
1. boolean computation on cumsum, eq, mul, sum 
2. negative index value on CrossEntropyLoss
=> Support llava inference example

benchmark/test_pointwise_perf.py, src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/flip.py, src/flag_gems/utils/pointwise_dynamic.py, tests/accuracy_utils.py, tests/test_unary_pointwise_ops.py
1. Support kwargs in pointwise_dynamic.
2. Add flip op as a pointwise op.
=> [Operator] Add flip op, and support kwargs in pointwise_dynamic

src/flag_gems/utils/pointwise_dynamic.py
1. Fix out_offset in pointwise_dynamic when rank is 0
=> [codegen] Fix out_offset in pointwise_dynamic when rank is 0

tests/test_special_ops.py
Now we only generate arange(hiddensize), each row use different index to shuffle
=> Fix topk unittest

.gitignore, CONTRIBUTING.md, CONTRIBUTING_cn.md, README_cn.md, tools/code_coverage/coverage.sh, tools/code_coverage/python_coverage.py, tools/model-test.sh, tools/op-unit-test.sh
- Add doc for CI
- Remove `ATTEMPT` var to make Coverage CI can rerun without relative CI
=> [Doc] Add doc for CI

.github/workflows/model-test.yaml, .github/workflows/op-unit-test.yaml, .github/workflows/python-coverage.yaml
Addition for https://github.com/FlagOpen/FlagGems/pull/182
=> Push checks

src/flag_gems/ops/div.py
try to import div_rz, div_rd, trunc from various paths
=> try to import div_rz, div_rd, trunc from various paths

.github/workflows/python-coverage.yaml
CI/CD
Bug Fix
Add checkout code for coverage in case that different runner pick the job
=> [no ci] add checkout code for coverage

src/flag_gems/ops/cumsum.py, tests/test_reduction_ops.py, tests/test_special_ops.py
Operator
Bug Fix
libentry import was accidentally removed in previous PR merge event. This is to add it back.
=> Undo libentry removal by merge conflicts

benchmark/test_reduction_perf.py
Benchmark
Refactor
split benchmark test of nonzero into float & int for data collection
=> [benchmark] split test of nonzero into two

tests/accuracy_utils.py, tests/test_binary_pointwise_ops.py, tests/test_blas_ops.py, tests/test_named_ops.py, tests/test_pointwise_type_promotion.py, tests/test_reduction_ops.py, tests/test_special_ops.py, tests/test_tensor_constructor_ops.py, tests/test_unary_pointwise_ops.py
[OP Test]
[Tests]
1. Modify test cases, reduce similar type test cases, increase test cases of different dimensions and size ranges, and try to unify the test shapes of similar operators.
2. Fix --device=cpu.
=> [Tests] Fix tests 1st ed.

benchmark/test_special_perf.py, src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/hstack.py, tests/accuracy_utils.py, tests/test_special_ops.py
Perf result on NV-A100
```
benchmark/test_special_perf.py::test_perf_hstack Operator hstack Performance Test (torch.float16)
1024                  0.016384            0.033792
6144                  0.043008            0.033792
11264                   0.0768            0.049152
16384                 0.111616            0.077824
21504                 0.144384             0.09728
26624                 0.176128            0.116736
31744                  0.20992            0.136192
36864                 0.241664            0.154624
41984                 0.275456            0.173056
47104                 0.308224            0.190464
52224                 0.342016            0.212992
57344 …
```
=> [Operator] Add hstack op

tests/accuracy_utils.py, tests/test_general_reduction_ops.py
OPTest
Refactor
Add a skip torch version utils function for pytest, supporting version patterns in the form of '=x.y', '<x.y', and '>x.y'
=> Add skip torch version in UT.

tests/test_binary_pointwise_ops.py
=> [Tests] Add non_contigpus input tests for repeat_interleave_self_int op

OperatorList.md, benchmark/test_pointwise_perf.py, benchmark/test_reduction_perf.py, tests/test_binary_pointwise_ops.py, tests/test_norm_ops.py, tests/test_reduction_ops.py, tests/test_special_ops.py
OP Test
Tests
Fix op name in tests and benchmark.
=> [Tests] Fix op name

OperatorList.md, benchmark/performance_utils.py, tests/conftest.py, tests/test_binary_pointwise_ops.py, tests/test_special_ops.py, tools/op-unit-test.sh, tools/pytest_mark_check.sh
OP Test
Tests
1. Record tests conditions in log file.
2. Fix op name.
3. Print mode in benchmark results.
4. Check pytest.mark.{OP_NAME} in CI.
=> [Tests] Fix tests 4th ed.

OperatorList.md, tests/test_norm_ops.py
OP Test
Tests
Reduce the testing time of _weight_norm_interface.
=> [Tests] Fix tests 5th ed

benchmark/test_reduction_perf.py
As title, fixed the test data shape in the gather performance test that could lead to errors.
=> [fix] Fix the input shape of gather's perf test

src/flag_gems/ops/vstack.py
Operator
New Feature
Modify the function parameter type declaration so that it can run in python 3.8
=> [Operator] Fix vstack

benchmark/test_special_perf.py, src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/upsample_bicubic2d_aa.py, tests/test_special_ops.py
Operator `_upsample_bicubic2d_aa`
New Feature
add operator  `_upsample_bicubic2d_aa`
A100
=> [Operator] Add _upsample_bicubic2d_aa op[MooreThreads]

src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/normal.py, tests/test_distribution_ops.py
Operator
Bug Fix
fix normal error for mean and std as float
delete normal_float_float
Issue #234
=> [bugfix] fix normal error of float input

benchmark/test_reduction_perf.py
=> [Operator] Add slice&select_scatter's benchmark

src/flag_gems/ops/max.py, tests/test_general_reduction_ops.py
=> fix a bug when the input of max is not contiguous

benchmark/attri_util.py, benchmark/conftest.py, benchmark/core_shapes.yaml, benchmark/performance_utils.py, benchmark/summary_for_plot.py, benchmark/test_special_perf.py
Benchmark 
Bug Fix
- Narrow benchmark size for UnaryReductionBenchmark
- Handle OOM exception
=> Narrow Benchmark Size for UnaryReductionBenchmark, Handle OOM Exception

benchmark/summary_for_plot.py
Benchmark
Other
delete suffix for datatype other than float. so that the script summarizes output data of all types into one operator, which makes performance collection convenient.
none
=> [benchmark] [no ci] update summary script

src/flag_gems/ops/masked_fill.py
Operator
Bug Fix
Fix an error introduced when merging code
related PR https://github.com/FlagOpen/FlagGems/pull/326
The code somehow did not merged as expected.
=> fix an error when merging code

src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/addmm.py, src/flag_gems/ops/mm.py
Other
New Feature
Key Changes:
Added new shapes from the `Qwen2.5-7b` and `LLaMA3-8b` configurations to the `pretune` function.
=> Update Pretune Shapes with Configurations from Qwen2.5-7b and LLaMA3-8b

tests/test_special_ops.py
OP Test
other
add int_dtypes and bool_dtypes for diag unit test and keep corresponding to benchmark
=> [ut] add dtypes for diag unit test

tests/accuracy_utils.py
=> move to_cpu before upcast for gpus lack fp64 support

src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/pad.py
Operator
Other
add the interface for constant_pad_nd and register it into aten independently.
thus the number of operators achieves 129.
=> [operator] add interface for constant_pad_nd

.github/workflows/python-coverage.yaml
CI/CD
Other
Testing coverage with a cpu only docker to save GPU resources
=> [CI/CD] Testing coverage with a cpu only docker

src/flag_gems/__init__.py, src/flag_gems/runtime/backend/_nvidia/__init__.py, src/flag_gems/runtime/backend/backend_utils.py, src/flag_gems/runtime/commom_utils.py, src/flag_gems/runtime/register.py
Other
New Feature 
Enhance the expression ability of operator library and user interaction ability
```python
import flag_gems as gems
gems.all_ops() 
#The user specifies that some operators are disabled
gems.use_gems(unused=['xxx'])
gems.enable(unused=['xxx'])
```
=> muti_backend_part_3 enhancement of ability

src/flag_gems/ops/count_nonzero.py, src/flag_gems/ops/cross_entropy_loss.py, src/flag_gems/ops/cummin.py, src/flag_gems/ops/instancenorm.py, src/flag_gems/ops/sort.py, src/flag_gems/ops/upsample_bicubic2d_aa.py, src/flag_gems/ops/upsample_nearest2d.py, src/flag_gems/runtime/backend/__init__.py, src/flag_gems/runtime/backend/_nvidia/tune_configs.yaml, src/flag_gems/runtime/register.py, tests/test_binary_pointwise_ops.py, tests/test_named_ops.py, tests/test_norm_ops.py, tests/test_reduction_ops.py, tests/test_special_ops.py, tests/test_unary_pointwise_ops.py
Other
Refactor 
modify some code to support muti_backend
=> modify code

benchmark/attri_util.py, benchmark/performance_utils.py, src/flag_gems/runtime/__init__.py
Other
Other
fix variable reference dependency error
=> [Fix bugs] Variable reference dependency error

benchmark/test_blas_perf.py
=> [bugfix] disable more shapes from blas benchmark

src/flag_gems/runtime/backend/_nvidia/__init__.py
Other
Bug Fix 
For muti_backend, Fix the bug
=> [Fix muti_backend bug]

src/flag_gems/runtime/backend/_nvidia/__init__.py, tests/test_named_ops.py
OP Test 
Bug Fix
Fix test_named_ops bug
since https://github.com/FlagOpen/FlagGems/pull/215 the usage --device=cpu change to --ref=cpu
=> [Fix bug] fix unittest bug

src/flag_gems/utils/pointwise_dynamic.py
Other
Refactor
before: 
```
pointwise_dynamic_bc18f5cd22033aff0a23e4e222371a310691d855865d0706ae5e94d1723ee0f99_rank_1_bptr_pid_1250495.py
```
after: 
```
pointwise_dynamic_bc18f5cd22033aff0a23e4e222371a310691d855865d0706ae5e94d1723ee0f99_add_func_kernel_rank_1_bptr_pid_1250495.py
```
=> Polish code gen filename

src/flag_gems/runtime/backend/_metax/__init__.py, src/flag_gems/runtime/backend/_metax/heuristics_config_utils.py, src/flag_gems/runtime/backend/_metax/ops/__init__.py, src/flag_gems/runtime/backend/_metax/ops/arange.py, src/flag_gems/runtime/backend/_metax/ops/exponential_.py, src/flag_gems/runtime/backend/_metax/ops/fill.py, src/flag_gems/runtime/backend/_metax/ops/full.py, src/flag_gems/runtime/backend/_metax/ops/full_like.py, src/flag_gems/runtime/backend/_metax/ops/groupnorm.py, src/flag_gems/runtime/backend/_metax/ops/isin.py, src/flag_gems/runtime/backend/_metax/ops/log_softmax.py, src/flag_gems/runtime/backend/_metax/ops/min.py, src/flag_gems/runtime/backend/_metax/ops/ones.py, src/flag_gems/runtime/backend/_metax/ops/outer.py, src/flag_gems/runtime/backend/_metax/ops/prod.py, src/flag_gems/runtime/backend/_metax/ops/sigmoid.py, src/flag_gems/runtime/backend/_metax/ops/tanh.py, src/flag_gems/runtime/backend/_metax/ops/unique.py, src/flag_gems/runtime/backend/_metax/ops/zeros.py, src/flag_gems/runtime/backend/_metax/tune_configs.yaml
=> [Operator]update metax custom op

src/flag_gems/ops/weightnorm.py
Operator
Other
store norm as float32 to improve precision
#402
=> [Operator] might slightly improve the precision

src/flag_gems/runtime/backend/__init__.py
Other
Other
```python
try: 
somecode
except RuntimeError 
```
Errors will still be reported
=> [fix bug] try except bug

src/flag_gems/ops/attention.py, tests/test_attention_ops.py
Operator
Bug Fix
qk_scale mistakenly got scaled up every iteration. Now fixed. 
Resolves #409
=> fix attention blowup.

benchmark/test_special_perf.py
Benchmark
Other
conv2d is not registered into aten library yet. the performance test of it should be skipped.
=> [Benchmark] skip conv2d perf test

src/flag_gems/runtime/backend/_iluvatar/heuristics_config_utils.py
=> [Iluvatar] Add vdot_heur_block_size

src/flag_gems/runtime/backend/_metax/heuristics_config_utils.py
Operator
Bug Fix
Add vdot op config in `heuristics_config_utils.py` in metax backend
=> [Metax] Add metax vdot heuristics config

src/flag_gems/ops/gather.py, src/flag_gems/ops/repeat.py, src/flag_gems/ops/tile.py, src/flag_gems/ops/zeros_like.py
Other
This pull request modifies the kernel names of several operators to ensure that their corresponding kernel names are more descriptive and easier to identify during debugging or profiling sessions.
=> update some kernel names

src/flag_gems/runtime/backend/_metax/tune_configs.yaml
Operator
Bug fix
Add conv op configs in metax backend (copied from nvida backend configs)
=> [Metax] Add metax backend conv tune config

src/flag_gems/runtime/backend/_iluvatar/tune_configs.yaml
=> [Iluvatar] Add conv2d tune config

benchmark/test_reduction_perf.py, benchmark/test_special_perf.py, benchmark/test_tensor_constructor_perf.py, build_flaggems.sh, clean_flaggems.sh, install_flaggems.sh, setup.py, src/flag_gems/ops/div.py, src/flag_gems/runtime/backend/_iluvatar/__init__.py, src/flag_gems/utils/libentry.py, test_flaggems.sh, tests/test_binary_pointwise_ops.py, tests/test_reduction_ops.py, tests/test_special_ops.py, tests/test_tensor_constructor_ops.py
=> [Muti backend] iluvatar backend patch

src/flag_gems/__init__.py, src/flag_gems/ops/index_select.py
Operator
Bug Fix
Fix the `index_select` bug when `dim` is not equal to `-1`.
- Resolves #455
=> Fix index_select Output Contiguity Issue

src/flag_gems/runtime/backend/_cambricon/tune_configs.yaml
=> cambricon: fix index put adopt error

tests/test_special_ops.py
=> mthreads: skip isin and fall back the change by mistake

tests/test_unary_pointwise_ops.py
Pytest Mark Repeat Miss Fixed In UnaryPointwise Test
=> Pytest Mark Repeat Miss Fixed

src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/div.py, src/flag_gems/runtime/backend/_kunlunxin/ops/index_put.py, src/flag_gems/runtime/backend/_kunlunxin/ops/scatter.py, tests/test_binary_pointwise_ops.py, tests/test_libentry.py, tests/test_norm_ops.py, tests/test_reduction_ops.py, tests/test_special_ops.py, tests/test_tensor_wrapper.py
Add IndexPut Op Supported && Add Test Skip
=> Add IndexPut Op Supported && Add Test Skip

tests/test_special_ops.py
=> add test seed for diag op

benchmark/test_special_perf.py, benchmark/test_unary_pointwise_perf.py, src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/elu.py, src/flag_gems/runtime/backend/_kunlunxin/ops/kron.py, tests/accuracy_utils.py, tests/test_special_ops.py
=> Add elu and kron op

src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/abs.py, src/flag_gems/runtime/backend/_kunlunxin/ops/add.py, src/flag_gems/runtime/backend/_kunlunxin/ops/bitwise_and.py, src/flag_gems/runtime/backend/_kunlunxin/ops/bitwise_not.py, src/flag_gems/runtime/backend/_kunlunxin/ops/bitwise_or.py, src/flag_gems/runtime/backend/_kunlunxin/ops/clamp.py, src/flag_gems/runtime/backend/_kunlunxin/ops/cos.py, src/flag_gems/runtime/backend/_kunlunxin/ops/div.py, src/flag_gems/runtime/backend/_kunlunxin/ops/erf.py, src/flag_gems/runtime/backend/_kunlunxin/ops/exp.py, src/flag_gems/runtime/backend/_kunlunxin/ops/gelu.py, src/flag_gems/runtime/backend/_kunlunxin/ops/mul.py, src/flag_gems/runtime/backend/_kunlunxin/ops/neg.py, src/flag_gems/runtime/backend/_kunlunxin/ops/pow.py, src/flag_gems/runtime/backend/_kunlunxin/ops/reciprocal.py, src/flag_gems/runtime/backend/_kunlunxin/ops/relu.py, src/flag_gems/runtime/backend/_kunlunxin/ops/rsqrt.py, src/flag_gems/runtime/backend/_kunlunxin/ops/sigmoid.py, src/flag_gems/runtime/backend/_kunlunxin/ops/silu.py, src/flag_gems/runtime/backend/_kunlunxin/ops/sin.py, src/flag_gems/runtime/backend/_kunlunxin/ops/sub.py, src/flag_gems/runtime/backend/_kunlunxin/ops/tanh.py, src/flag_gems/runtime/backend/_kunlunxin/utils/pointwise_dynamic.py, tests/test_binary_pointwise_ops.py
=> [kunlunxin] add inplace bin op support

src/flag_gems/runtime/backend/_kunlunxin/ops/mse_loss.py
=> [kunlunxin] fix mse

benchmark/core_shapes.yaml
Benchmark
Bug Fix
large shape will cause out of memory for kron benchmark. this pr deletes the last 3 shapes and preserves 5 shapes for core mode.
=> [bugfix] delete test shape that cause oom

tests/test_special_ops.py
=> [Kunlunxin] add topk supported

.github/workflows/code-format-check.yml, .github/workflows/gems-test-on-hopper.yaml, .github/workflows/gems-test-on-metax.yaml
=> Run ci on Hopper and metax

.github/workflows/python-coverage.yaml, tools/code_coverage/report_coverage.sh
CI/CD
Other
Add PR coverage report url
=> Add PR coverage report url 

benchmark/test_reduction_perf.py, benchmark/test_select_and_slice_perf.py, benchmark/test_special_perf.py
topk, upsample_nearest2d, log_softmax, index_select, var_mean
=> [Kunlunxin] benchmark: add some ops support

src/flag_gems/runtime/backend/_kunlunxin/fused/gelu_and_mul.py, src/flag_gems/runtime/backend/_kunlunxin/fused/silu_and_mul.py
=> [Kunlunxin] add silu_and_mul_grad & gelu_and_mul_grad

src/flag_gems/runtime/backend/_kunlunxin/ops/max.py, src/flag_gems/runtime/backend/_kunlunxin/ops/min.py
=> [Kunlunxin] Fix min max kernel

.github/workflows/code_scan.yaml
=> Add code scan CI

src/flag_gems/runtime/backend/_kunlunxin/ops/bmm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/mm.py
=>  [Kunlunxin] Update blas kernel

src/flag_gems/runtime/backend/_arm/__init__.py, src/flag_gems/runtime/backend/_arm/heuristics_config_utils.py, src/flag_gems/runtime/backend/_arm/ops/__init__.py, src/flag_gems/runtime/backend/_arm/ops/add.py, src/flag_gems/runtime/backend/_arm/ops/gelu.py, src/flag_gems/runtime/backend/_arm/tune_configs.yaml
Other
New Feature 
tune config arm cpu
=> arm tune config

src/flag_gems/runtime/backend/_kunlunxin/ops/bmm.py
=> [Kunlunxin] Fix typo

src/flag_gems/__init__.py
Operator
Bug Fix
Fix register bitwise_and_.Tensor name
=> Fix register bitwise_and_.Tensor name

tests/accuracy_utils.py, tests/test_reduction_ops.py
OP Test
Other
Fix index_put and scatter add uts
=> Fix index_put and scatter add uts

src/flag_gems/runtime/backend/_metax/ops/min.py, src/flag_gems/runtime/backend/_metax/tune_configs.yaml
Operator
Bug Fix
1. Add tune config of kron and index_put in metax backend.
2. Fix min op in metax backend.
=> [Metax] Fix metax backend op

src/flag_gems/ops/rms_norm.py, tests/test_norm_ops.py
=> Add rmsnorm backward

src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/linspace.py
=> [kunlunxin] add linspace

src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/fill.py, tests/test_unary_pointwise_ops.py
https://github.com/FlagOpen/FlagGems/issues/493
=> Fix fill and add fill_

src/flag_gems/runtime/backend/_kunlunxin/ops/contiguous.py, src/flag_gems/runtime/backend/_kunlunxin/ops/max.py
=> fix contiguous

src/flag_gems/runtime/backend/_kunlunxin/ops/cumsum.py, tests/test_reduction_ops.py
=> [kunlunxin] add cumsum supported

src/flag_gems/runtime/backend/_kunlunxin/ops/rms_norm.py, tests/test_norm_ops.py
=> [kunlunxin] Add rms bwd

src/flag_gems/runtime/backend/_kunlunxin/ops/layernorm.py
=> [kunlunxin] fix layernorm

src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/log.py
=> [kunlunxin] Add log supported

benchmark/conftest.py, src/flag_gems/runtime/backend/__init__.py
=> [Bug Fix]fix codestyle

src/flag_gems/runtime/backend/_kunlunxin/ops/rms_norm.py
=> [kunlunxin] fix rmsnorm backward

.gitignore, cmake/FindTorch.cmake, ctests/CMakeLists.txt, doc/build_flaggems_with_c_extensions.md
Other
Bug Fix
1. Update CMake to use `_GLIBCXX_CXX11_ABI` from torch to ensure ABI consistency.
2. update documentation.
=> Update CMake and documentation

src/flag_gems/runtime/backend/_kunlunxin/ops/nonzero.py, tests/test_reduction_ops.py
=> add nonzero and open masked_select test

.clang-format, .pre-commit-config.yaml, ctests/CMakeLists.txt, ctests/test_triton_blas.cpp, ctests/test_triton_pointwise.cpp, ctests/test_triton_reduction.cpp, include/flag_gems/operators.h, include/flag_gems/utils.h, lib/CMakeLists.txt, lib/add.cpp, lib/mm.cpp, lib/sum.cpp, src/flag_gems/csrc/cstub.cpp, triton_src/mm.py
Operator
- Add mm cpp wrapper and unit test
- Add cpp clang-format rules for pre-commit
- Test result:
=> [CPP runtime]  Add mm cpp wrapper

benchmark/test_special_perf.py, src/flag_gems/runtime/backend/_kunlunxin/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/argmax.py, src/flag_gems/runtime/backend/_kunlunxin/ops/cumsum.py, src/flag_gems/runtime/backend/_kunlunxin/ops/multinomial.py, tests/test_distribution_ops.py, tests/test_special_ops.py
=> [kunlunxin] add multinomial supprorted

cmake/Dependencies.cmake, ctests/CMakeLists.txt, ctests/test_triton_norm.cpp, include/flag_gems/operators.h, include/flag_gems/utils.h, lib/CMakeLists.txt, lib/rms_norm.cpp, lib/utils.cpp, src/flag_gems/csrc/cstub.cpp, triton_src/rms_norm.py
=> [C++ wrapper] rms_norm operator

src/flag_gems/runtime/backend/_kunlunxin/ops/layernorm.py
=> [kunlunxin] add buffersize limit

src/flag_gems/runtime/backend/__init__.py, src/flag_gems/runtime/backend/_hygon/ops/__init__.py, src/flag_gems/runtime/backend/_hygon/ops/div.py, src/flag_gems/runtime/backend/_hygon/ops/gelu.py, src/flag_gems/runtime/backend/_hygon/ops/pow.py, src/flag_gems/runtime/backend/_hygon/ops/silu.py, src/flag_gems/runtime/backend/_hygon/tune_configs.yaml
=> [hygon] fix accuracy error for  hygon backend ops

.github/workflows/gems-cpp-extension.yaml, cmake/Dependencies.cmake, ctests/test_triton_reduction.cpp
CI/CD
Bug Fix
Fix lib_torch_example commit id in cmake
=> Add cpp ci and fix lib_torch_example commit

docs/build_flaggems_with_c_extensions.md, src/flag_gems/csrc/cstub.cpp
Operator
Bug Fix
Fix mis-registration of fused_add_rms_norm
Fix PR #577
=> [C++ wrapper] fix mis registration of fused_add_rms_norm

src/flag_gems/runtime/backend/_kunlunxin/ops/any.py, src/flag_gems/runtime/backend/_kunlunxin/ops/arange.py, src/flag_gems/runtime/backend/_kunlunxin/ops/vector_norm.py
Optimization operator block：any,arange,vector_norm
=> block size change: any, arange, vector_norm

benchmark/performance_utils.py, benchmark/test_reduction_perf.py, benchmark/test_select_and_slice_perf.py, src/flag_gems/runtime/backend/_kunlunxin/ops/cat.py, src/flag_gems/runtime/backend/_kunlunxin/ops/gather.py, src/flag_gems/runtime/backend/_kunlunxin/ops/isin.py, src/flag_gems/runtime/backend/_kunlunxin/ops/max.py, src/flag_gems/runtime/backend/_kunlunxin/ops/pad.py
=> [kunlunxin] fix pad

src/flag_gems/runtime/backend/_kunlunxin/ops/layernorm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/unique.py
=> [kunlunxin] fix unique & fix layernorm

src/flag_gems/runtime/backend/_kunlunxin/ops/addmm.py
=> [kunlunxin] Update blas addmm

src/flag_gems/runtime/backend/_hygon/ops/div.py
=> [hygon] fix accuracy error for trunc div

src/flag_gems/runtime/backend/_kunlunxin/ops/cat.py, src/flag_gems/runtime/backend/_kunlunxin/ops/pad.py, tests/test_special_ops.py
=> [KUNLUN] Fix Cat in Pad

benchmark/test_select_and_slice_perf.py
=> [kunlunxin] open some  benchmark

src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/angle.py, src/flag_gems/runtime/backend/_kunlunxin/ops/dot.py, src/flag_gems/runtime/backend/_kunlunxin/ops/index_put.py, src/flag_gems/runtime/backend/_kunlunxin/ops/nan_to_num.py, src/flag_gems/runtime/backend/_kunlunxin/ops/polar.py, tests/test_reduction_ops.py, tests/test_unary_pointwise_ops.py
=> add [angle, dot, index_put, nan_to_num, polar] supported

tests/test_unary_pointwise_ops.py
=> revert fill_ cpu

src/flag_gems/runtime/backend/_kunlunxin/ops/all.py, src/flag_gems/runtime/backend/_kunlunxin/ops/normal.py, src/flag_gems/runtime/backend/_kunlunxin/ops/rand.py, src/flag_gems/runtime/backend/_kunlunxin/ops/rand_like.py, src/flag_gems/runtime/backend/_kunlunxin/ops/randn.py, src/flag_gems/runtime/backend/_kunlunxin/ops/randn_like.py
=> Fix speedup  rand

src/flag_gems/runtime/backend/_kunlunxin/ops/any.py
=> [kunlunxin] Speed any

cmake/Dependencies.cmake, cmake/FindTorch.cmake, docs/build_flaggems_with_c_extensions.md, pyproject.toml
Other
Other
Use latest master branch of libtorch_example since embedding of python interpreter has been "fixed" now.
=> update dependency of libtorch_example

src/flag_gems/runtime/backend/_kunlunxin/ops/all.py, src/flag_gems/runtime/backend/_kunlunxin/ops/any.py
=> [kunlunxin] fix any buffer_size_limit param

src/flag_gems/runtime/backend/_kunlunxin/ops/unique.py
=> [kunlunxin] fix unique op macro

src/flag_gems/runtime/backend/_metax/ops/__init__.py, src/flag_gems/runtime/backend/_metax/ops/arange.py, src/flag_gems/runtime/backend/_metax/ops/exponential_.py, src/flag_gems/runtime/backend/_metax/ops/fill.py, src/flag_gems/runtime/backend/_metax/ops/full.py, src/flag_gems/runtime/backend/_metax/ops/full_like.py, src/flag_gems/runtime/backend/_metax/ops/groupnorm.py, src/flag_gems/runtime/backend/_metax/ops/index_select.py, src/flag_gems/runtime/backend/_metax/ops/log_softmax.py, src/flag_gems/runtime/backend/_metax/ops/min.py, src/flag_gems/runtime/backend/_metax/ops/ones.py, src/flag_gems/runtime/backend/_metax/ops/outer.py, src/flag_gems/runtime/backend/_metax/ops/prod.py, src/flag_gems/runtime/backend/_metax/ops/repeat_interleave.py, src/flag_gems/runtime/backend/_metax/ops/sigmoid.py, src/flag_gems/runtime/backend/_metax/ops/tanh.py, src/flag_gems/runtime/backend/_metax/ops/zeros.py, tests/test_general_reduction_ops.py
Operator
1. optimize data access pattern in index select.
2. implement a new repeat_interleave kernel
3. modify metax op debug messages to debug easier
4. add max_int test into metax accuracy tests
=> [METAX]  update metax backend operators and tests

src/flag_gems/runtime/backend/_kunlunxin/ops/all.py
=> [kunlunxin]fix-all

benchmark/test_binary_pointwise_perf.py, benchmark/test_reduction_perf.py, benchmark/test_special_perf.py, benchmark/test_unary_pointwise_perf.py, src/flag_gems/runtime/backend/_mthreads/ops/__init__.py, src/flag_gems/runtime/backend/_mthreads/ops/addmm.py, src/flag_gems/runtime/backend/_mthreads/ops/bmm.py, src/flag_gems/runtime/backend/_mthreads/ops/isin.py, src/flag_gems/runtime/backend/_mthreads/ops/mm.py, src/flag_gems/runtime/backend/_mthreads/ops/unique.py, src/flag_gems/runtime/backend/_mthreads/ops/utils.py, tests/test_binary_pointwise_ops.py, tests/test_blas_ops.py, tests/test_distribution_ops.py, tests/test_norm_ops.py, tests/test_special_ops.py, tests/test_unary_pointwise_ops.py
=> Mthreads: Add mm kernel for mthreads backend, and enable some ops and disable some ops.

src/flag_gems/runtime/backend/_hygon/ops/__init__.py, src/flag_gems/runtime/backend/_hygon/ops/div.py, src/flag_gems/runtime/backend/_hygon/ops/isclose.py
=> [hygon] fix accuracy error for 'isclose' and 'allclose'

benchmark/performance_utils.py, benchmark/test_binary_pointwise_perf.py, src/flag_gems/fused/gelu_and_mul.py, src/flag_gems/ops/angle.py, src/flag_gems/ops/div.py, src/flag_gems/ops/gelu.py, src/flag_gems/ops/isinf.py, src/flag_gems/ops/isnan.py, src/flag_gems/ops/nan_to_num.py, src/flag_gems/ops/pow.py, src/flag_gems/ops/tanh.py, src/flag_gems/ops/vector_norm.py, src/flag_gems/runtime/backend/__init__.py, src/flag_gems/runtime/backend/_ascend/__init__.py, src/flag_gems/runtime/backend/_ascend/heuristics_config_utils.py, src/flag_gems/runtime/backend/_ascend/tune_configs.yaml, src/flag_gems/runtime/backend/device.py, src/flag_gems/runtime/commom_utils.py, tests/test_binary_pointwise_ops.py, tests/test_blas_ops.py, tests/test_general_reduction_ops.py, tests/test_reduction_ops.py, tests/test_special_ops.py, tests/test_unary_pointwise_ops.py
BACKEND
New Feature
Init ascend backend.
=> [BACKEND] Init ascend backend 20250512

src/flag_gems/runtime/backend/_metax/heuristics_config_utils.py, src/flag_gems/runtime/backend/_metax/ops/__init__.py, src/flag_gems/runtime/backend/_metax/ops/masked_fill.py, src/flag_gems/runtime/backend/_metax/ops/ones.py, src/flag_gems/runtime/backend/_metax/ops/ones_like.py, src/flag_gems/runtime/backend/_metax/ops/resolve_conj.py, src/flag_gems/runtime/backend/_metax/ops/zeros.py, src/flag_gems/runtime/backend/_metax/ops/zeros_like.py
=> [METAX] Improve metax ops performance

src/flag_gems/runtime/backend/_kunlunxin/ops/all.py, src/flag_gems/runtime/backend/_kunlunxin/ops/any.py, src/flag_gems/runtime/backend/_kunlunxin/ops/full.py
=> [KUNLUN] Speed Up Full/Full Like, Fix All/Any

README.md, README_cn.md, docs/build_flaggems_with_c_extensions.md
=> [Doc] update README with citation

src/flag_gems/runtime/backend/_kunlunxin/ops/full.py, src/flag_gems/runtime/backend/_kunlunxin/ops/full_like.py, src/flag_gems/runtime/backend/_kunlunxin/ops/ones.py, src/flag_gems/runtime/backend/_kunlunxin/ops/ones_like.py, src/flag_gems/runtime/backend/_kunlunxin/ops/zeros.py, src/flag_gems/runtime/backend/_kunlunxin/ops/zeros_like.py
=> [KUNLUN] Speed Up Full/Ones/Zeros

benchmark/test_distribution_perf.py
OP Test
Bug Fix
In the benchmark of normal op, use `torch.normal` as the reference.
Resolves #611
=> fix benchmark of normal: use torch.normal as the reference

src/flag_gems/ops/addmm.py, src/flag_gems/ops/all.py, src/flag_gems/ops/amax.py, src/flag_gems/ops/any.py, src/flag_gems/ops/bmm.py, src/flag_gems/ops/max.py, src/flag_gems/ops/mean.py, src/flag_gems/ops/min.py, src/flag_gems/ops/mm.py, src/flag_gems/ops/prod.py, src/flag_gems/ops/sum.py, src/flag_gems/runtime/backend/_nvidia/tune_configs.yaml, src/flag_gems/utils/libentry.py
Other
New Feature
1. allow autotuner to choose configs according to log of key arguments
2. set shared config cache for similar operators
=> [LibTuner] simplify autotuner for faster inference

src/flag_gems/runtime/backend/_metax/ops/__init__.py, src/flag_gems/runtime/backend/_metax/ops/addmm.py, src/flag_gems/runtime/backend/_metax/ops/bmm.py, src/flag_gems/runtime/backend/_metax/ops/log_softmax.py, src/flag_gems/runtime/backend/_metax/ops/mm.py, src/flag_gems/runtime/backend/_metax/ops/upsample_nearest2d.py, src/flag_gems/runtime/backend/_metax/tune_configs.yaml
Operator
Bug Fix & performance optimization
1. Speedup addmm, bmm and mm
2. Fix log_softmax op
=> [METAX] Update metax backend ops

src/flag_gems/runtime/backend/_cambricon/ops/arange.py, src/flag_gems/runtime/backend/_cambricon/ops/argmax.py, src/flag_gems/runtime/backend/_cambricon/ops/bmm.py, src/flag_gems/runtime/backend/_cambricon/ops/cumsum.py, src/flag_gems/runtime/backend/_cambricon/ops/fill.py, src/flag_gems/runtime/backend/_cambricon/ops/gather.py, src/flag_gems/runtime/backend/_cambricon/ops/index_select.py, src/flag_gems/runtime/backend/_cambricon/ops/masked_fill.py, src/flag_gems/runtime/backend/_cambricon/ops/max.py, src/flag_gems/runtime/backend/_cambricon/ops/mean.py, src/flag_gems/runtime/backend/_cambricon/ops/mm.py, src/flag_gems/runtime/backend/_cambricon/ops/scatter.py, src/flag_gems/runtime/backend/_cambricon/ops/softmax.py, src/flag_gems/runtime/backend/_cambricon/ops/sum.py, src/flag_gems/runtime/backend/_cambricon/ops/tile.py, src/flag_gems/runtime/backend/_cambricon/ops/topk.py, src/flag_gems/runtime/backend/_cambricon/tune_configs.yaml, src/flag_gems/runtime/backend/_cambricon/utils/pointwise_dynamic.py
Operator 
Performance Optimization 
cambricon: change autotune to libtuner to improve performance
strategy相关参数添加依赖 https://github.com/FlagOpen/FlagGems/pull/587/
=> cambricon: change autotune to libtuner

tests/test_norm_ops.py
=> Weightnorm ci test

src/flag_gems/runtime/backend/_kunlunxin/ops/normal.py, src/flag_gems/runtime/backend/_kunlunxin/ops/randn.py, src/flag_gems/runtime/backend/_kunlunxin/ops/randn_like.py, src/flag_gems/runtime/backend/_kunlunxin/utils/block_size_utils.py, src/flag_gems/runtime/backend/_kunlunxin/utils/pointwise_dynamic.py
=> [kunlunxin] Fix randn

tests/test_norm_ops.py
=> [test] skip ut of weight_norm_backward

src/flag_gems/ops/fill.py
Operator
Bug Fix
Fix fill_tensor cpu tensor error
=> Fix fill_tensor cpu tensor error

src/flag_gems/modules/normalization.py, src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/groupnorm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/to.py, src/flag_gems/runtime/backend/_kunlunxin/ops/weightnorm.py, tests/test_binary_pointwise_ops.py, tests/test_norm_ops.py
=> [kunlunxin] Fix weightnorm & Fix groupnorm & Add to_dtype()

src/flag_gems/runtime/backend/_kunlunxin/ops/to.py, src/flag_gems/runtime/backend/_kunlunxin/utils/codegen_config_utils.py, src/flag_gems/runtime/backend/_kunlunxin/utils/pointwise_dynamic.py
=> [kunlunxin] fix to_dtype err

src/flag_gems/ops/gelu.py, src/flag_gems/ops/randperm.py, src/flag_gems/ops/topk.py, src/flag_gems/runtime/backend/_cambricon/ops/topk.py, src/flag_gems/runtime/backend/_kunlunxin/ops/randperm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/topk.py, src/flag_gems/utils/libentry.py, tests/test_libentry.py
CI/CD
Bug Fix
Fix triton3.3 error
=> Fix triton3.2/3.3 error

src/flag_gems/ops/exponential_.py, src/flag_gems/ops/multinomial.py, src/flag_gems/ops/normal.py, src/flag_gems/ops/randperm.py, src/flag_gems/ops/uniform.py, src/flag_gems/runtime/backend/_cambricon/ops/exponential_.py, src/flag_gems/runtime/backend/_cambricon/ops/multinomial.py, src/flag_gems/runtime/backend/_cambricon/ops/normal.py, src/flag_gems/runtime/backend/_cambricon/ops/uniform.py, src/flag_gems/runtime/backend/_kunlunxin/ops/exponential_.py, src/flag_gems/runtime/backend/_kunlunxin/ops/multinomial.py, src/flag_gems/runtime/backend/_kunlunxin/ops/normal.py, src/flag_gems/runtime/backend/_kunlunxin/ops/randperm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/uniform.py, src/flag_gems/runtime/backend/_metax/ops/exponential_.py, src/flag_gems/utils/random_utils.py
Operator
Bug Fix
Previous sampling functions were not using generator argument when they were passed in. This breaks certain e2e test. This issue is fixed in this PR.
=> Random sampler functions support pass-in generator

docs/installation.md, docs/pointwise_dynamic.md
Other
- add doc for installation; 
- update docs for pointwise_dynamic to include more details.
=> [DOC] add doc for installation; update docs for pointwise_dynamic 

docs/how_to_use_flaggems.md
=> add how_to_use_flaggems.md

docs/how_to_use_flaggems.md, examples/integration_gems_with_vllm.py
Other
- Replaced the detailed platform listing for non-NVIDIA hardware with a direct link to the corresponding documentation section.
- Fixed formatting issues in code examples (e.g., indentation alignment).
- Updated the `libtuner` section with clearer explanations and improved instructions for using `pretune.py.`
=> User Guidance Documentation Updates

src/flag_gems/ops/eye.py, src/flag_gems/ops/eye_m.py, src/flag_gems/ops/glu.py, src/flag_gems/ops/lerp.py, src/flag_gems/runtime/backend/_kunlunxin/fused/weight_norm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/eye.py, src/flag_gems/runtime/backend/_kunlunxin/ops/eye_m.py, src/flag_gems/runtime/backend/_kunlunxin/ops/glu.py, src/flag_gems/runtime/backend/_metax/ops/nonzero.py, src/flag_gems/runtime/backend/_metax/ops/polar.py, src/flag_gems/runtime/backend/_metax/ops/upsample_nearest2d.py
Other
replace logging.debug with logger.debug
=> [reformat] record ops calling by logger

benchmark/test_reduction_perf.py, src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py, src/flag_gems/ops/cummax.py, src/flag_gems/ops/cummin.py, src/flag_gems/utils/triton_lang_extension.py, tests/test_reduction_ops.py
Operator
New Feature & Performance Optimization
New Feature: cummax
Performance Optimization: cummin
Resolves #320 
Huge performance boost compared to Pytorch. 🚀
Testing GPU card: H800
Triton version: 3.1.0
Pytorch version: 2.4.1
CUDA version: 12.4
- **[After optimization]** ✅ cummax and cummin
- **[Before optimization]** cummax and cummin
=> [Operator] support and optimize cummax and cummin

src/flag_gems/utils/triton_driver_helper.py
UTILS
Bug Fix
Fix except bug in triton_driver_helper.
=> [UTILS] Fix except bug in triton_driver_helper

src/flag_gems/ops/full.py, src/flag_gems/ops/full_like.py
Operator 
Other
Implement full&full_like op using pointwise_dynamic
full(pointwise_dynamic)
full(ori)
full_like(pointwise_dynamic)
full_like(ori)
=> [AdvancedCompiler]Add full&full_like(pointwise_dynamic)

src/flag_gems/runtime/backend/_kunlunxin/fused/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/fused/concat_and_cache_mla.py, src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/cummax.py, src/flag_gems/runtime/backend/_kunlunxin/ops/lerp.py, tests/test_binary_pointwise_ops.py
=> [kunlunxin] add lerp concat_and_cache_mla and cummax

src/flag_gems/runtime/backend/_kunlunxin/fused/concat_and_cache_mla.py, src/flag_gems/runtime/backend/_kunlunxin/fused/outer.py, src/flag_gems/runtime/backend/_kunlunxin/fused/reshape_and_cache.py, src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/batch_norm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/mv.py, src/flag_gems/runtime/backend/_kunlunxin/ops/scatter.py, tests/test_attention_ops.py, tests/test_quant.py
=> [kunlunxin] fix outer,mv,scatter,batch_norm; add reshape_and_cache

benchmark/test_special_perf.py
Benchmark
Other
remove sorting of bool values since torch 2.4 does not support it on cuda
=> remove sorting of bool values since torch 2.4 does not support it on cuda

src/flag_gems/ops/attention.py
Operator
Bug fix
no tensor allocation needed for `out`.
=> fix flash_attn_varlen_func.

src/flag_gems/ops/sort.py
Operator
Bug Fix
- fix unexpected type promotion in sort, use scalar tensor as it has explicit type(or else it would not work in triton 3.1)
=> fix unexpected type promotion in sort, use scalar tensor as it has explicit type

src/flag_gems/runtime/backend/_cambricon/heuristics_config_utils.py
update cambricon code based on master
=> cambricon: update cambricon code based on master

src/flag_gems/ops/upsample_nearest2d.py, src/flag_gems/runtime/backend/_iluvatar/heuristics_config_utils.py, src/flag_gems/runtime/backend/_nvidia/heuristics_config_utils.py
=> [Iluvatar] optimize upsample_nearest2d

src/flag_gems/patches/patch_vllm_all.py
Other
Bug Fix
Fix flash attn forward patch
=> Fix flash attn forward patch

src/flag_gems/runtime/backend/_cambricon/ops/__init__.py, src/flag_gems/runtime/backend/_cambricon/ops/select_scatter.py, src/flag_gems/runtime/backend/_cambricon/ops/slice_scatter.py, tests/test_reduction_ops.py
Operator
Bug Fix
update kernel after merge master
=> cambricon: adapt kernel after merge master

benchmark/test_blas_perf.py, benchmark/test_select_and_slice_perf.py
=> [kunlunxin] tmp disable some operator

src/flag_gems/runtime/backend/_mthreads/heuristics_config_utils.py, tests/test_norm_ops.py, tests/test_reduction_ops.py
OP Test 
Other
1. update heuristics_config_utils.py in mthreads backend
2. enable scatter, scatter_ and layernorm ops
=> [mthreads] update the config file and enable some supported operators.

benchmark/test_generic_pointwise_perf.py, benchmark/test_reduction_perf.py, benchmark/test_select_and_slice_perf.py, tests/test_norm_ops.py
=> [KUNLUNXIN]tmp disable some operators  and open operator

src/flag_gems/runtime/backend/_ascend/heuristics_config_utils.py
=> [Ascend]Add heuristics_config for ascend

include/flag_gems/operators.h, lib/fill.cpp, src/flag_gems/csrc/cstub.cpp
Operator
Other
Change the signature of inplace fill accordign to ATen's schema
=> fix fill operator registration

src/flag_gems/ops/index.py, src/flag_gems/utils/libentry.py
Operator
Bug Fix
Fix save tune config error when vllm exit
=> Fix save tune config error when vllm exit

src/flag_gems/runtime/__init__.py, src/flag_gems/runtime/backend/_ascend/heuristics_config_utils.py, src/flag_gems/runtime/configloader.py
=> [MutiBackend] Change the mechanism for get vendor heuristics_config

src/flag_gems/ops/attention.py, src/flag_gems/ops/flash_kernel.py, tests/test_attention_ops.py
Operator & OP Test
New Feature
Add GQA support for `ops.scaled_dot_product_attention`.
Add more test cases for `test_sdpa_legacy`.
=> add forward gqa support for `scaled_dot_product_attention` & more tests cases for `test_sdpa_legacy`

src/flag_gems/runtime/backend/_aipu/ops/__init__.py, src/flag_gems/runtime/backend/_aipu/ops/cumsum.py, src/flag_gems/runtime/backend/_aipu/ops/multinomial.py
Operator
aipu changes TILE in normed_cumsum op, which is called by multinomial op.
=> [BACKEND] aipu change TILE in normed_cumsum

src/flag_gems/runtime/backend/_cambricon/fused/gelu_and_mul.py, src/flag_gems/runtime/backend/_cambricon/fused/weight_norm.py, src/flag_gems/runtime/backend/_cambricon/heuristics_config_utils.py, src/flag_gems/runtime/backend/_cambricon/ops/cummin.py, src/flag_gems/runtime/backend/_cambricon/tune_configs.yaml
Operator
Bug Fix 
adapt heuristics_config after merge master
=> cambricon: adapt cambricon after merge master

src/flag_gems/utils/libentry.py
Other
New Feature
Add align32 to support more sparse key computation strategies.
=> implement align32 strategy

src/flag_gems/utils/libentry.py, tests/test_libentry.py
libcache test
Bug Fix
The current libcache is unable to handle the issue of multiple child processes writing concurrently upon exit.
=> Update libcache store function

docs/ctest_in_flaggems.md
use correct building flag in ctest document
=> [Document]: modify ctest build option

src/flag_gems/fused/__init__.py, src/flag_gems/fused/silu_and_mul.py, src/flag_gems/patches/patch_vllm_all.py
Operator
New Feature
Patch vllm silu_and_mul
=> Patch vllm silu_and_mul

tests/accuracy_utils.py, tests/test_special_ops.py
OP Test
Bug Fix
Fix cpu tests in test_special_ops. In some cases, the CPU version of arange in PyTorch may produce incorrect results.
=> [TEST] Fix cpu tests in test_special_ops

src/flag_gems/utils/libentry.py
Other
Bug Fix
Support triton 3.4
=> Support triton 3.4

benchmark/test_reduction_perf.py, tests/test_reduction_ops.py
OP Test
Other
Unskip var_mean accuracy and performance tests for weekly tests, since we fix the issue in mcTriton now.
=> [METAX] unskip var_mean tests

src/flag_gems/fused/moe_align_block_size.py, src/flag_gems/patches/patch_vllm_all.py
Operator
Fix moe_align_block_size re-compile to speed-up qwen3-30B-A3B
=> Fix moe_align_block_size re-compile

src/flag_gems/utils/libentry.py
LibEntry
Refactor
Remove the ATTRS list, and use the signature of triton.Config to see the parameter is `numargs` or `kwargs`.
=> remove attrs

benchmark/test_norm_perf.py, benchmark/test_select_and_slice_perf.py, benchmark/test_special_perf.py, benchmark/test_unary_pointwise_perf.py, src/flag_gems/fused/concat_and_cache_mla.py, src/flag_gems/runtime/backend/_mthreads/heuristics_config_utils.py, src/flag_gems/runtime/backend/_mthreads/tune_configs.yaml, tests/test_attention_ops.py, tests/test_general_reduction_ops.py, tests/test_libentry.py, tests/test_reduction_ops.py, tests/test_special_ops.py, tests/test_unary_pointwise_ops.py
OP Test
Other
adaptation for musa backend
* enable perf
- layer_norm
- batch_norm
* disable perf
- sort
- masked_select
* enable test
- diagonal
- concat_and_cache_mla
- batch_norm
- scaled_dot_product_attention
* disable test
- sort
- quantile
- conv1d
- masked_select
=> [mthreads] musa backend adaptation

tests/test_unary_pointwise_ops.py
=> [ut] add ut for sqrt_

benchmark/test_unary_pointwise_perf.py, src/flag_gems/runtime/backend/_mthreads/ops/addmm.py, src/flag_gems/runtime/backend/_mthreads/ops/bmm.py, src/flag_gems/runtime/backend/_mthreads/ops/mm.py, src/flag_gems/runtime/backend/_mthreads/ops/utils.py, src/flag_gems/runtime/backend/_mthreads/tune_configs.yaml, tests/test_unary_pointwise_ops.py
Operator 
* optimize performance in musa backend
- mm
- addmm
- bmm
* enable op
- glu_backward
=> [mthreads] optimize mm/addmm/bmm ops in musa backend

src/flag_gems/ops/mm.py, src/flag_gems/runtime/backend/_nvidia/tune_configs.yaml
Operator
Performance optimization
update config space of mm with the best choices from @sgjzfzzf 's experiment.
=> [op] update mm configs

src/flag_gems/__init__.py, src/flag_gems/ops/__init__.py
Operator 
Bug Fix 
Register for index_add_.
=> Register index_add_ 

benchmark/test_blas_perf.py, src/flag_gems/runtime/backend/_mthreads/fused/__init__.py, src/flag_gems/runtime/backend/_mthreads/fused/cross_entropy_loss.py, src/flag_gems/runtime/backend/_mthreads/heuristics_config_utils.py, src/flag_gems/runtime/backend/_mthreads/ops/__init__.py, src/flag_gems/runtime/backend/_mthreads/ops/attention.py, src/flag_gems/runtime/backend/_mthreads/ops/dropout.py, src/flag_gems/runtime/backend/_mthreads/ops/ones.py, src/flag_gems/runtime/backend/_mthreads/ops/ones_like.py, src/flag_gems/runtime/backend/_mthreads/ops/rand.py, src/flag_gems/runtime/backend/_mthreads/ops/rand_like.py, src/flag_gems/runtime/backend/_mthreads/ops/randn.py, src/flag_gems/runtime/backend/_mthreads/ops/randn_like.py, src/flag_gems/runtime/backend/_mthreads/ops/zeros.py, src/flag_gems/runtime/backend/_mthreads/ops/zeros_like.py, src/flag_gems/runtime/backend/_mthreads/tune_configs.yaml, tests/test_attention_ops.py, tests/test_blas_ops.py, tests/test_distribution_ops.py, tests/test_norm_ops.py, tests/test_reduction_ops.py, tests/test_special_ops.py
Other
Bug Fix
* fix illegal memory error by custom op
- ones
- ones_like
- dropout
- rand
- rand_like
- zeros
- zeros_like
* skip ops
- attention
- cross_entropy_loss
* update config file
* temp disable some ops for updating
=> [MTHREADS] adaptation in musa backend

src/flag_gems/utils/libentry.py
LibCache
Bug Fix
Previous implementation will lead to sqlite3 error when a connection is shared among multi-threads. We set `check_same_thread` as `False` to allow it shared among threads, and provide `threading.Lock` to protect it manually.
=> add locks to protect single connection shared in multi-threads

benchmark/conftest.py, tests/test_reduction_ops.py
=> [KUNLUNXIN]change param input

src/flag_gems/runtime/backend/_kunlunxin/ops/fill.py
=> [kunlunxin] fix fill scalar

src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/addcdiv.py, src/flag_gems/runtime/backend/_kunlunxin/ops/celu.py, src/flag_gems/runtime/backend/_kunlunxin/ops/logspace.py
=> [kunlunxin] add addcdiv & celu & logspace

benchmark/models_benchmark/README.md, benchmark/models_benchmark/online.sh, benchmark/models_benchmark/online_with_gems.sh, benchmark/models_benchmark/requirements.txt
Benchmark
New Feature
support  FlagScale server in `models_benchmark`
=> add scale server support in model_benchmark

src/flag_gems/fused/reshape_and_cache_flash.py
Operator
Other
Add c_ext for reshape_and_cache_flash
=> Add c_ext for reshape_and_cache_flash

tests/test_pointwise_type_promotion.py
=> [HYGON] skip case of runtime error

src/flag_gems/runtime/backend/_aipu/heuristics_config_utils.py, src/flag_gems/runtime/backend/_aipu/tune_configs.yaml, tests/test_general_reduction_ops.py, tests/test_special_ops.py
=> [aipu] Update aipu backend

src/flag_gems/ops/flash_kernel.py, src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py, src/flag_gems/runtime/backend/_kunlunxin/ops/addmm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/addr.py, src/flag_gems/runtime/backend/_kunlunxin/ops/argmax.py, src/flag_gems/runtime/backend/_kunlunxin/ops/attention.py, src/flag_gems/runtime/backend/_kunlunxin/ops/diag.py, src/flag_gems/runtime/backend/_kunlunxin/ops/dropout.py, src/flag_gems/runtime/backend/_kunlunxin/ops/flash_api.py, src/flag_gems/runtime/backend/_kunlunxin/ops/flash_kernel.py, src/flag_gems/runtime/backend/_kunlunxin/ops/full.py, src/flag_gems/runtime/backend/_kunlunxin/ops/groupnorm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/isin.py, src/flag_gems/runtime/backend/_kunlunxin/ops/layernorm.py, src/flag_gems/runtime/backend/_kunlunxin/ops/pad.py, src/flag_gems/runtime/backend/_kunlunxin/ops/rand_like.py, src/flag_gems/runtime/backend/_kunlunxin/ops/randn_like.py, src/flag_gems/runtime/backend/_kunlunxin/ops/unique.py
=> [kunlunxin] fix argmax & update addr op

benchmark/test_special_perf.py
Benchmark
Other
unify the opname of test for pad
=> unify the opname of test for pad

src/flag_gems/runtime/backend/_mthreads/ops/mm.py
=> [MTHREADS] Fix mm op to support Qwen3-8B.
