- README.md
- README_cn.md
- benchmark/test_pointwise_perf.py
- tests/test_binary_pointwise_ops.py
- tests/test_unary_pointwise_ops.py
> [Document] README Feature: automatic code generation

- src/flag_gems/ops/layernorm.py
layer_norm_backward_kernel does not work correctly with BLOCK_ROW_SIZE > 1. This PR fixes this bug.
> [bugfix] fix error in layer_norm_backward_kernel

- src/flag_gems/ops/dropout.py
This PR fixes an error on some backends where casting philox offsets to tl.uint64 is not supported.
> Dropout uses int32 philox if int64 is not supported 

- benchmark/performance_utils.py
- benchmark/test_blas_perf.py
- benchmark/test_fused_perf.py
- benchmark/test_reduction_perf.py
- src/flag_gems/utils/pointwise_dynamic.py
1. move specific arg-gen functions into corresponding tests
2. add test_fused_perf.py (including gelu&mul, silu&mul, skip_layernorm, skip_rmsnorm)
> [Test] Reconstruct benchmark & support fused ops

- .pre-commit-config.yaml
- benchmark/test_blas_perf.py
- benchmark/test_fused_perf.py
- benchmark/test_pointwise_perf.py
- benchmark/test_reduction_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/dropout.py
- tests/test_binary_pointwise_ops.py
- tests/test_blas_ops.py
- tests/test_reduction_ops.py
- tests/test_special_ops.py
- tests/test_unary_pointwise_ops.py
Remove python version and ignore of F403 & E722
> [format] Remove python version and ignore of F403 & E722

- src/flag_gems/ops/all.py
- src/flag_gems/ops/amax.py
- src/flag_gems/ops/any.py
- src/flag_gems/ops/mean.py
- src/flag_gems/ops/sum.py
- src/flag_gems/ops/var_mean.py
- src/flag_gems/ops/vector_norm.py
- src/flag_gems/utils/__init__.py
- src/flag_gems/utils/shape_utils.py
1. implement Welford var_mean and two-pass kernels to take place of the low-perf var_meak_kernel
2. implement compress_dim function for multiple reduction dims
3. remove the limit of commit python version
> [Operator] premute for reduction tensors & welford var_mean

- .github/workflows/python-test.yaml
- src/flag_gems/utils/libentry.py
- tests/test_libentry.py
fix libentry:
1. ensure that decorator cascading is working as expected, i.e. inner decorator can use arguments provided by outer decorator
2. ensure that grid function can use all the arguments provided by decorators(Autotuner & Heuristics)
3. simplify LibEntry, extract captured constant arguments from CompiledKernel, instead of traversing layers of decorator.
> [bugfix] fix libentry on argument processing

- src/flag_gems/ops/layernorm.py
- src/flag_gems/ops/sigmoid.py
- src/flag_gems/ops/tanh.py
- src/flag_gems/ops/vector_norm.py
1. implement two-pass kernels for all reduce vector_norm
2. avoid upcasting of half precision for tanh and sigmoid when gradient is not required
3. expand config tuning space for LayerNorm
> [Operator] optimization of vector_norm, tanh, sigmoid, layernorm

- src/flag_gems/ops/softmax.py
- tests/test_reduction_ops.py
Use different kernels (inner & non_inner) for softmax forward & backward.
1. inner: for reduction the last dim(and the input is preprocessed to be contiguous)
2. inner: for reduce along other dimensions(and the input is preprocessed to be contiguous)
Both have `ONE_TILE_PER_CTA` static condition
1. when `ONE_TILE_PER_CTA` is True, load only one tile per cta without looping over reduction dim
2. when `ONE_TILE_PER_CTA` is False, use online softmax normalizer algorithm to save one swipe over the input.
The `non_inner` kernels now have a better task partitioning to achieve better coalescing in global memory access. For a contiguous tensor with shape `(M, N, K)`, and the reduction is applied in axis-1, if `K>1`, it is considered a non-inner reduction.
In this case, the shape of the data tile …
> work in progress optimize softmax: use better task partitioning

- benchmark/performance_utils.py
- src/flag_gems/fused/skip_layernorm.py
- src/flag_gems/fused/skip_rms_norm.py
- src/flag_gems/ops/addmm.py
- src/flag_gems/ops/cross_entropy_loss.py
- src/flag_gems/ops/dropout.py
- src/flag_gems/ops/groupnorm.py
- src/flag_gems/ops/layernorm.py
- src/flag_gems/ops/rms_norm.py
- src/flag_gems/ops/triu.py
- src/flag_gems/ops/var_mean.py
- src/flag_gems/ops/vector_norm.py
- src/flag_gems/utils/libentry.py
1. modified libentry arguments collection, cache key generation and constexpr collection
2. specify dns arguments for operators
3. works for triton 2.2 and 2.3
> [operator] fix libentry to support triton 2.3

- src/flag_gems/ops/dropout.py
This PR applies the following changes to dropout.
-  Uses the 128bit Philox output to generate four dropout masks instead of one in the current version.
-  Replaces libentry and autotune with simple triton.heuristics for better API performance.
Improved performance on A100 is show below.
dropout-performance:
M       torch         gems
0  5.000000e+02    0.199681     0.230627
1  4.096000e+03    1.646302     2.031746
2  1.638400e+04    8.094861     7.757576
3  6.553600e+04   28.151202    31.148290
4  1.000000e+05   40.716611    46.992483
5  1.000000e+09  952.747469  1326.879422
> Improve dropout performance by unrolling 4xint random masks.

- src/flag_gems/ops/sigmoid.py
- src/flag_gems/utils/pointwise_dynamic.py
generate gsl(grid-stride-loop) style pointwise kernel to avoid grid_s…ize exceeding the max grid size.
example jit function
```python
@triton.jit
def _jit_function(
in0_ptr: tl.tensor, # of tl.pointer_type
in1_ptr: tl.tensor, # of tl.pointer_type
out0_ptr: tl.tensor, # of tl.pointer_type
in0_stride0: int, in0_stride1: int, in0_stride2: int, # strides for in0
in1_stride0: int, in1_stride1: int, in1_stride2: int, # strides for in1
out0_stride0: int, out0_stride1: int, out0_stride2: int, # strides for out0
s0: int, s1: int, s2: int, # task_space
num_tasks: int,
tile_size: tl.constexpr,
tiles_per_cta,
):
pid = tl.program_id(0)
num_ctas = tl.num_programs(0)
init_tid = pid * tile_size + tl.arange(0, tile_size)
for j in range(0, tiles_per_cta):
tid = init_tid + j * tile_size * num_ctas
mask = …
```
> [codegen] generate gsl(grid-stride-loop) style pointwise kernel 

- src/flag_gems/fused/gelu_and_mul.py
- src/flag_gems/ops/gelu.py
- src/flag_gems/ops/groupnorm.py
- src/flag_gems/ops/isinf.py
- src/flag_gems/ops/isnan.py
- src/flag_gems/ops/pow.py
- src/flag_gems/ops/sigmoid.py
- src/flag_gems/ops/silu.py
- src/flag_gems/ops/tanh.py
- src/flag_gems/ops/vector_norm.py
try to import tl.math functions from different path at various versions of triton
triton moves some of the function in `tl.math` to `tl.extra.cuda.libdevice`, which *breaks* backward compatibility, so we work around it.
Since PR #98 changes the way to inline function, now we can directly *call* a JITFunction in another JITFunction.
but from where should we import the inlined function? well, ... try except
```python
try:
from triton.language.extra.cuda.libdevice import rsqrt
except ImportError:
try:
from triton.language.math import rsqrt
except ImportError:
from triton.language.libdevice import rsqrt
```
Never mask a symbol(redefine it with the same name) which is used in JITFunction, since the `DependencyFinder` would find the latest value.
For example, `src/flag_gems/ops/tanh.py` …
> try to import tl.math functions from different paths

- benchmark/performance_utils.py
- benchmark/test_blas_perf.py
- benchmark/test_fused_perf.py
- benchmark/test_pointwise_perf.py
- benchmark/test_reduction_perf.py
- benchmark/test_special_perf.py
1. remove pytest parameter dtype and initialize data types in Benchmark constructor. this allow vendors to collect speedup data easier.
2. scale up performance test shape to over 1M.
> [Benchmark] simplify benchmark and increase perf test scale

- src/flag_gems/ops/argmax.py
- src/flag_gems/ops/bmm.py
- src/flag_gems/ops/cross_entropy_loss.py
- src/flag_gems/ops/cumsum.py
- src/flag_gems/ops/dropout.py
- src/flag_gems/ops/log_softmax.py
- src/flag_gems/ops/max.py
- src/flag_gems/ops/min.py
- src/flag_gems/ops/mm.py
- src/flag_gems/ops/prod.py
- src/flag_gems/ops/rand.py
- src/flag_gems/ops/randn.py
- src/flag_gems/ops/softmax.py
- src/flag_gems/ops/var_mean.py
For python before version 3.10.10, lambda expression might cause python inspect error. It is fixed [here](https://github.com/python/cpython/pull/99654) , but requires higher version.
To support python3.8, we redefine all lambda expressions in triton.Heuristics as functions.
> [Runtime] Heuristic expression allowing python3.8

- src/flag_gems/ops/sigmoid.py
Avoid calling external library in rhs of assignemnts to tl.constexpr, as disallowed in triton3.0.0, use numeric literal instead.
See https://github.com/triton-lang/triton/issues/4321 for more details.
> Avoid calling external library in rhs of assignemnts to tl.constexpr

- benchmark/test_pointwise_perf.py
rename benchmark of operators like bitwise ops, allclose as xx_int.
> [Benchmark] rename benchmark for integer operator tests

- src/flag_gems/ops/rand.py
- src/flag_gems/ops/rand_like.py
- src/flag_gems/ops/randn.py
We observed that the kernel of the rand class operator writes data four times the size of a BLOCK each time, but the grid issued for processing is handled based on the amount of data each kernel processes per BLOCK. Consequently, we emulated the dropout mechanism to modify the grid processing logic, and similarly, we adapted the seed calculation parameters based on the dropout approach.
> [Operator] Fix rand/randn/rand_like grid and seed error

- benchmark/performance_utils.py
- benchmark/test_reduction_perf.py
* [benchmark] add argument 'is_backward' to class 'Benchmark', we can set 'is_backward' true to perf backward process of some operation.
> [Benchmark] add backward mode for benchmark

- benchmark/test_special_perf.py
- pyproject.toml
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/dropout.py
- src/flag_gems/ops/exponential_.py
- tests/test_special_ops.py
Added Triton function for inplace operator tensor.exponential_. 
The output value range is (0, \infin)
> Exponential added.

- src/flag_gems/ops/amax.py
- src/flag_gems/ops/argmax.py
- src/flag_gems/ops/triu.py
- src/flag_gems/utils/shape_utils.py
1. fix amax, armax and triu, use int64 indexing when the largest tens…or's size_in_bytes exceed int32's max;
2. change the tiling scheme for argmax to loop in the reduction dimension, instead of data-size-dependent-tile-size
> Use int64 indexing when needed & fix argmax

- src/flag_gems/utils/libentry.py
- src/flag_gems/utils/pointwise_dynamic.py
- tests/test_libentry.py
The present multithreading support in Triton is not yet in a ready state. For example, a simple use case is throwing a bunch of Python threads to run a model on multiple devices in parallel. However, this usage can easily break Triton as its runtime is not properly serialized. As a result, FlagGems using libentry is prone to race conditions when gems are called in parallel threads without proper locking. This PR brings jit serialization into libentry to enable race free invocations of all libentry wrapped functions.
> Making libentry thread safe

- tests/test_specific_ops.py
Do test according to specific ops.
usage：
```
python3.11 test_specific_ops.py --name add      # for a specific op "add"
python3.11 test_specific_ops.py --all           # for all ops in the op list
```
> [Test] Test for op

- tests/test_distribution_ops.py
- tests/test_tensor_constructor_ops.py
In k-s test, scipy do not support bfloat16, Since now we have seperate k-s test to another file, bfloat16 should be tested in  rand, randn & uniform.
> [Test] Add bfloat16 test for  rand, randn & uniform

- src/flag_gems/ops/embedding.py
the padding_idx has been processed in `torch.nn.fucntional.padding`
> Remove process of padding_idx

- tests/test_named_ops.py
```
usage: test_named_ops.py [-h] [--all] [--name NAME] [--device {cuda,cpu}]
options:
-h, --help           show this help message and exit
--all                test for all ops in the op list
--name NAME          test for a specific op
--device {cuda,cpu}  device to run reference tests on. Choose 'cuda' or 'cpu'. Default is 'cuda'.
```
> [test] Add device option for named_op

- tests/test_special_ops.py
Ensure scalars are float32 in test cases for dropout. Now dropout is computed in the following formula:
`out = tensor * mask / (1-p)`
In our test cases, the reference is also compute in thay.
But in some cases, `1-p` have different byte representations depending on how it is computed.
1. `(1 - p)` when `p` is a native python floating point number then cast to float32;
2. `(1 - p)` when `p` and `1` are both numpy 32bit floating point number then cast to float32;
Thus, `tensor / (1-p)` may have have different results when `1-p` have different representations.
> ensure scalars are float32 in test cases for dropout

- src/flag_gems/ops/cross_entropy_loss.py
- tests/test_special_ops.py
1. fix device error in test:    
pytest -sv test_special_ops.py  --device cpu
2. fix possible numerical accuracy overflow in cross entropy loss, if inp.dtype is f16 and sum(out) > max(f16), the cvt may cause inf, then the multiply result is inf;  but multiply mean_num first may avoid inf
> [test]: fix embedding/topk test cpu mode and celoss inf bug

- src/flag_gems/ops/pad.py
- src/flag_gems/ops/tile.py
Use a singleton to avoid generating code every time tile or pad is called
> use a singleton to avoid generating code every time

- benchmark/test_pointwise_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/repeat.py
- tests/accuracy_utils.py
- tests/test_unary_pointwise_ops.py
Operator
New Feature
Add repeat op.
similar to https://github.com/FlagOpen/FlagGems/pull/148
> [Operator] Add repeat op

- benchmark/test_reduction_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/cumsum.py
- src/flag_gems/ops/masked_select.py
- src/flag_gems/utils/__init__.py
- tests/test_reduction_ops.py
Operator
New Feature
Add masked_select op
```
benchmark/test_reduction_perf.py::test_masked_select Operator masked_select Performance Test (torch.float16)
1024                  0.080896            0.229376
6144                  0.223232            0.415744
11264                 0.365568              0.4608
16384                 0.503808            0.515072
21504                 0.646144            0.596992
26624                  0.78336            0.713728
31744                 0.924672            0.830464
36864                  1.06394            0.948224
41984                  1.20218             1.06598
47104                  1.33632             1.18272
52224                  1.47661 …
```
> [Operator] Add masked_select op[IluvatarCorex]

- README.md
- README_cn.md
- benchmark/test_pointwise_perf.py
- benchmark/test_reduction_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/outer.py
- tests/test_blas_ops.py
Operator
Other
use mv instead of mm for outer backward. thus ci/cd could finish in a short time.
and reduce tests of addmm as well, cause it doesn't need thousands of cases to prove the accuracy.
the cuda performance of outer backward isn't improved indeed. optimization to do on mv.
> [Operator] simplify outer backward

- benchmark/performance_utils.py
- benchmark/test_pointwise_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/div.py
- tests/accuracy_utils.py
- tests/test_binary_pointwise_ops.py
Op
Bug Fix and new feature
Added the Pytorch/numpy typed remainder and floor divide for integers. The summarized procedure for the Triton Pytorch conversion for floordiv is:
```
def floordiv(x, y):
if x % y != 0 and x < 0 ^ y < 0:
return x // y - 1
else:
return x // y
def _remainder(x, y):
if x % y != 0 and x < 0 ^ y < 0:
return r + y
else:
return r
```
Performance for bs=1024 on A100:
```
benchmark/test_pointwise_perf.py Operator floor_div Performance Test (torch.int16)
1024                  0.016096            0.014752
6144                  0.042016            0.040128
11264                 0.067136            0.066112
16384                 0.089888            0.089728
21504 …
```
> Floordiv int

- tests/test_reduction_ops.py
[OP Test]
[Buf Fix]
convert input tensor and index to specific device for reference. otherwise the ref_out will not be on CPU when option --device is cpu.
> [bugfix] convert inp of index_select to enable cpu mode

- src/flag_gems/ops/index_select.py
- tests/test_reduction_ops.py
Operator
Bug Fix
We found an issue with the definition of `cols_offsets` in the `index_select` operator. When `N` is larger than `BLOCK_N`, the indices cannot cover all the input columns.
- **Test 1:** With the input dimension of `REDUCTION_SHAPES=(4096,n)`,  we forced `BLOCK_N=2048`. When `dim=0`, `test_reduction_ops.py::test_accuracy_index_select` failed.
- **Test 2:** We increased the original input dimension to `REDUCTION_SHAPES=(4096*m,n)`. When `dim=0`, `test_reduction_ops.py::test_accuracy_index_select` failed.
```
======================================== short test summary info =========================================
FAILED tests/test_reduction_ops.py::test_accuracy_index_select[dtype0-0-shape0] - AssertionError
FAILED tests/test_reduction_ops.py::test_accuracy_index_select[dtype …
```
> [Operator] fix index_select bug [MooreThreads]

- benchmark/test_special_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/cat.py
- tests/test_special_ops.py
```
benchmark/test_special_perf.py::test_perf_cat Operator cat Performance Test (torch.float16)
1024                  0.018432            0.016384
6144                   0.05632            0.045056
11264                 0.095232            0.069632
16384                 0.134144            0.093184
21504                  0.17408             0.11776
26624                 0.212992            0.141312
31744                 0.253952            0.165888
36864                 0.293888            0.192512
41984                 0.333824            0.217088
47104                 0.374784             0.24064
52224                  0.41472            0.264192
57344 …
```
> [Operator] Add cat op

- benchmark/test_pointwise_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/repeat_interleave.py
- tests/test_binary_pointwise_ops.py
```
benchmark/test_pointwise_perf.py::test_perf_repeat_interleave_self_int Operator repeat_interleave_self_int Performance Test (torch.float16)
1024                  0.019456            0.012288
6144                   0.05632            0.036864
11264                 0.096256             0.06144
16384                 0.136192            0.084992
21504                 0.177152            0.169984
26624                 0.216064            0.171008
31744                    0.256            0.172032
36864                 0.295936            0.246784
41984                 0.334848            0.247808
47104                 0.374784            0.249856
52224 …
```
> [Operator] Add repeat_interleave_self_int op

- tests/test_blas_ops.py
OP Test
Other
Add reduce_dim=M for `test_accuracy_mv`.
Since mv is an operator where reduction is involved, reduce_dim should be considered in tests for correctness, following our convention in other tests.
No changes to the operator.
> add reduce_dim=M for tests for mv op

- src/flag_gems/ops/layernorm.py
- tests/test_norm_ops.py
Operator
Optimize forward pass of layernorm, now we use one of the three kernels dependending on reduction size
1. Persistent multiline kernel: when `reduction size <=128`;
2. Persistent kernel: when `128 < reduction size <=4096`. It uses 1d tile and saves some indexing & masking;
3. Loop Kernel: when `reduction size > 4096`. 
It uses a variant of welford algorithm for computing variance, which saves an extra loading of the input. 
It also uses other tricks like reversing the second loop to increase L2 hit rate when reduction size is not too large; 
Evicting more eagerly in the second loop; 
Specializing the last iteration to avoid masking on other iteration.
Here are the benchmark results on RTX-3090.
cpu mode timing
```text
test_reduction_perf.py Operator …
```
> optimize layernorm forward

- benchmark/test_special_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/vstack.py
- tests/test_special_ops.py
add vstack operator
perf of some cases on NV A100:
```
benchmark/test_special_perf.py Operator vstack Performance Test (torch.float16)
1024                  0.017408            0.011264
6144                  0.057344            0.032768
11264                  0.09728            0.053248
16384                 0.136192            0.070656
21504                 0.177152            0.090112
26624                 0.217088             0.10752
31744                 0.257024            0.125952
36864                 0.297984            0.144384
41984                 0.338944            0.162816
47104                 0.379904            0.181248
52224                 0.420864             0.19968 …
```
> [Operator] Add vstack op [MooreThreads]

- src/flag_gems/ops/layernorm.py
- src/flag_gems/utils/type_utils.py
- tests/test_norm_ops.py
Operator
Bug Fix
fix layer_norm_backward: save mean and rstd in float32 when the inputs are in half-precision floating point dtypes to avoid numerical instability or errors
NOTE: Aten's implementation also saves mean and rstd in fp32 in these cases
> save mean and rstd in float32 when the inputs are in half-precision fp types

- benchmark/test_pointwise_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/repeat_interleave.py
- tests/test_unary_pointwise_ops.py
```
benchmark/test_pointwise_perf.py::test_perf_repeat_interleave_tensor 
Operator repeat_interleave_tensor Performance Test (dtype=torch.int32, mode=cuda)
Size    Torch Latency (ms)    Gems Latency (ms)    Gems Speedup
---------------------------------------------------------------
1024              0.095232             0.259072           0.368
6144              0.094208             0.277504           0.339
11264             0.093184             0.279552           0.333
16384             0.095232             0.278528           0.342
21504             0.100352             0.278528            0.36
26624               0.1024             0.280576           0.365
31744             0.103424               0.2816           0.367
36864             0.103424             0.285696 …
```
> [Operator] Add repeat_interleave_tensor

- src/flag_gems/ops/weightnorm.py
[Operator]
[Bug Fix]
weight norm with eps as dns argument and constexpr at the same time doesn't work on triton 2.1.
since eps is not necessary for kernel compilation, here mark it as dns.
Issue from Iluvatar
> [bugfix] mark eps as dns arg instead of constexpr

- tests/test_norm_ops.py
- tests/test_special_ops.py
OP Test
Bug Fix
upcast input tensor to fp64 for cpu reference. so that weight_norm and upsample_bicubic2d_aa could run fp16 tests in cpu mode.
> [bugfix] upcast input tensor to fp64 for cpu reference

- benchmark/test_special_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/upsample_nearest2d.py
- tests/accuracy_utils.py
- tests/test_special_ops.py
Operator `upsample_nearest2d`
New Feature
https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/native_functions.yaml#L12777C6-L12777C7
func: upsample_nearest2d(Tensor self, SymInt[2] output_size, float? scales_h=None, float? scales_w=None) -> Tensor
> [Operator] Add upsample_nearest2d op [MooreThreads]

- benchmark/test_special_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/index_select.py
- src/flag_gems/ops/repeat_interleave.py
- tests/test_special_ops.py
```
Operator repeat_interleave_self_tensor Performance Test (dtype=torch.float16, mode=cuda)
Size    Torch Latency (ms)    Gems Latency (ms)    Gems Speedup
---------------------------------------------------------------
1024              0.336896              20.0387          0.0168
6144               1.53498              20.9459          0.0733
11264               2.7648              20.4554           0.135
16384              4.12979              21.6965            0.19
21504                5.376              21.4784            0.25
26624              7.02874              22.4543           0.313
31744              8.03123              22.8055           0.352
36864              8.09677              22.5853           0.358
41984              10.2134              23.1731 …
```
> [Operator] Add repeat_interleave_self_tensor

- benchmark/test_tensor_constructor_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/randperm.py
- src/flag_gems/ops/sum.py
- src/flag_gems/ops/topk.py
- tests/test_named_ops.py
- tests/test_tensor_constructor_ops.py
Add randperm operator
- add two branches for randperm, one is bitonic method for small cases, the other is radix mathod for larger cases
- radix method is composed of radix sort + shuffle, but for perf issue, we do a **block shuffle** rather than adjacent shuffle as pytorch cuda: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/Randperm.cu#L106
- the perf is 3-4 times slower than pytorch cuda cub, the key reasons I think are: 1. triton doesn't support **shared memory atomic** primitive, so  "digit_hist_kernel" is much slower than cub; 2. triton can't control threads level operation, so lookback of radix sort is **serialized** rather than parallelized in cub;
- the above understanding may not be accurate, any suggestions are welcome. The following table shows perf of …
> [Operator] Add randperm op [MooreThreads]

- benchmark/test_special_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/diag.py
- tests/test_special_ops.py
Operator
New Feature
Add diag op kernel and related tests
Resolves #252 
Operator: diag  Performance Test (dtype=torch.bfloat16, mode=cuda, level=comprehensive)
|Size    |     Torch Latency (ms)  |  Gems Latency (ms)  |       Gems Speedup    |     Size Detail|
|----------|------------------------------|-------------------------|------------------|-------|
|N/A               |    0.005120|            0.004096 |              1.250   |       ([torch.Size([64, 64])], {'diagonal': -4})|
|N/A                |   0.007168  |          0.006144   |            1.167     |     ([torch.Size([4096, 4096])], {'diagonal': 4})|
|N/A                 |  0.006144    |        0.006144     |          1.000       |   ([torch.Size([4])], {'diagonal': 4})|
|N/A                  | 0.012288      |      0.011264 …
> [Operator] Add diag op and related tests(#252)

- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/where.py
- tests/test_binary_pointwise_ops.py
Operator
Bug Fix and New Feature
Now `where` is able to handle cross device inputs with ndim=0.
Error case,
```
cond = torch.randint(0, 2, (10, ), dtype=torch.bool, device='cuda')
torch.where(cond, torch.tensor(0), torch.tensor(1))
```
> [Fix] where errors on zero dim cpu tensor inputs

- benchmark/test_reduction_perf.py
- src/flag_gems/ops/cross_entropy_loss.py
- tests/test_reduction_ops.py
Operator
apply fusion on celoss kernel and sum kernel of weight.
avoid memory copy from device to host by disabling context saving when input tensor doesn't require gradient.
achieve over 200% relative performance on average compared to aten (only 13% before)
A100-benchmark performance
> [Optimization] CrossEntropyLoss

- src/flag_gems/ops/embedding.py
- tests/test_special_ops.py
Operator
Bug Fix
Fix embedding op backward with bf16. Before atomic_add(bf16), we convert both ptr and data to fp32.
- Resolves #305
> [Operator] Fix embedding op backward with bf16

- src/flag_gems/ops/softmax.py
- tests/test_reduction_ops.py
Operator
Bug Fix
Fix online softmax where there are inf's in the input. Since online softmax algorithm is used in loop-style softmax-kernel.
The update rule for m & z is(note that we use a binary combine & reduce in epilogue style):
```python
m = tl.full([TILE_N], value=float("-inf"), dtype=tl.float32)
z = tl.full([TILE_N], value=0.0, dtype=tl.float32)
for ...:
inp = tl.load(input_ptr + n_offsets)
m_new = tl.maximum(m, inp)
z = z * tl.exp(m - m_new) + tl.exp(inp - m_new))
m = m_new
```
It is possible that the new_new is still `-inf`, thus `m - m_new` and `inp - m_new` are nan. To fix this, we need to skip those `-inf`s, they contribute nothing to the normalizer z.
Here is the fix.
```python
all_neg_inf = m_new == float("-inf")
z = tl.where(all_neg_inf, z, z * tl.exp(m - m_new) + …
```
> fix online softmax where there are inf's in the input

- src/flag_gems/ops/dropout.py
- src/flag_gems/ops/exponential_.py
- src/flag_gems/ops/multinomial.py
- src/flag_gems/ops/ones.py
- src/flag_gems/ops/rand.py
- src/flag_gems/ops/randn.py
- src/flag_gems/ops/randperm.py
- src/flag_gems/ops/uniform.py
- src/flag_gems/utils/libentry.py
Operator
Bug Fix
remove tle for those operators using philox.
uniform function doesn't support int64 as offset temporarily.
> [bugfix] replace tle with tl for operators using philox

- src/flag_gems/ops/full.py
- src/flag_gems/ops/full_like.py
- src/flag_gems/ops/ones.py
- src/flag_gems/ops/zeros.py
- tests/test_tensor_constructor_ops.py
Operator
Bug Fix
1. When dtype is not provided, dtype should be set according to fill_value.
2. When dtype is provided, fill_value should be check for overflow.
3. If dtype is not bool and fill_value is bool, fill_value should be converted to int.
4. If dtype is float, the truncation of fill_value should be noted.
5. The default device should be "cpu".
> [Operator] Fix full & full_like op

- src/flag_gems/utils/pointwise_dynamic.py
- tests/test_pointwise_dynamic.py
- tests/test_special_ops.py
Other
Bug Fix
Support zero-sized tensor for Pointwise Dynamic.
Previously, pointwise functions would launch a kernel to do the job. The task partition logic involves a function that try to find a tile size with numel limit and prefer larger tile size for inner dimensions.
```python
def heuristics_for_tile_size(max_tile_size, *sizes):
ndim = len(sizes)
tile_sizes = [0 for _ in range(ndim)]
for i in range(ndim):
size = sizes[ndim - 1 - i]
tile_size = min(max_tile_size, triton.next_power_of_2(size))
tile_sizes[ndim - 1 - i] = tile_size
max_tile_size = max(1, max_tile_size // tile_size)
return tuple(tile_sizes)
```
It has a lot of divisions, when the size is 0, it would raise `DivisionByZero`s.
We fix it by skipping kernel launch and task partitioning when the number of tasks(numel of the …
> support zero-sized tensor for PointwiseDynamic

- benchmark/test_special_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/diagonal.py
- tests/test_special_ops.py
Close https://github.com/FlagOpen/FlagGems/issues/314
> [Operator] Add diagonal backward

- benchmark/test_binary_pointwise_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/logical_and.py
- tests/test_binary_pointwise_ops.py
Operator
New Feature
Add logical_and gems op
A100-40G
```
Operator: logical_and  Performance Test (dtype=torch.int16, mode=cuda,level=comprehensive)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup               TFLOPS         Size Detail
------------------------------------------------------------------------------------------------------------------------
SUCCESS               3.849536            3.926912               0.980               0.547          [torch.Size([1073741824]), torch.Size([1073741824])]
SUCCESS               0.007168            0.006816               1.052               0.001          [torch.Size([64, 64]), torch.Size([64, 64])]
SUCCESS               0.079296            0.079104               1.002               0.424 …
```
> Add logical_and gems op

- benchmark/test_binary_pointwise_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/logical_xor.py
- tests/test_binary_pointwise_ops.py
Operator
New Feature
Add logical_xor gems op
A100-40G
```
Operator: logical_xor  Performance Test (dtype=torch.int16, mode=cuda,level=comprehensive)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup               TFLOPS         Size Detail
------------------------------------------------------------------------------------------------------------------------
SUCCESS               3.848320            3.928992               0.979               0.547          [torch.Size([1073741824]), torch.Size([1073741824])]
SUCCESS               0.006752            0.006784               0.995               0.001          [torch.Size([64, 64]), torch.Size([64, 64])]
SUCCESS               0.080096            0.079104               1.013               0.424 …
```
> Add logical_xor gems op

- benchmark/attri_util.py
- benchmark/test_special_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/isin.py
- src/flag_gems/ops/sort.py
- src/flag_gems/ops/topk.py
- src/flag_gems/ops/unique.py
- tests/test_special_ops.py
Operator
New Feature
Add sort op.
This PR is modified according to the PR #222 submitted by MARD1NO (ZZK) from SiliconFlow.
> [Operator] Add sort op

- src/flag_gems/ops/log_softmax.py
- src/flag_gems/ops/max.py
- src/flag_gems/ops/min.py
- src/flag_gems/ops/prod.py
- src/flag_gems/runtime/backend/_nvidia/tune_configs.yaml
- tests/test_reduction_ops.py
Bug Fix
Use loop kernel for min, max, prod, log_softmax to allow larger reduction size.
We leave persistent/loop(stream)/split algorithms and better strategy to support different layouts for further optimization.
> use loop kernel for min, max, prod, log_softmax to allow larger reduction size

- src/flag_gems/ops/instancenorm.py
triton 2.1 do not support num_warps in kernel signature
> remove num_warps=4 in kernel signature to compatible with triton 2.1

- src/flag_gems/ops/groupnorm.py
- src/flag_gems/ops/layernorm.py
- tests/test_norm_ops.py
Operator
Bug Fix
process None pointer in triton kernel and backward function
https://github.com/FlagOpen/FlagGems/issues/323
> [operator] group_norm and layer_norm support weight&bias as None

- src/flag_gems/utils/codegen_config_utils.py
- src/flag_gems/utils/pointwise_dynamic.py
Other
Other
1. support codegen_config specialization 
The vendors only needs to config CODEGEN_COFIGS in FlagGems/src/flag_gems/utils/codegen_config_utils.py
```python
CODEGEN_COFIGS = {
vendors.NVIDIA: CodeGenConfig(
512,
(65536, 65536, 65536),
32,
True,
prefer_1d_tile=int(triton.__version__[0]) < 3,
)
}
```
> [muti_backend]support codegen_config specialization

- benchmark/performance_utils.py
- benchmark/test_reduction_perf.py
Benchmark
Other
triton before version 3.0 doesn't support cummin.
mark the parameters of cummin as skipped.
> [benchmark] skip perf test of cummin when triton < 3.0

- examples/model_bert_test.py
- src/flag_gems/ops/attention.py
- src/flag_gems/ops/topk.py
- src/flag_gems/ops/upsample_bicubic2d_aa.py
- src/flag_gems/runtime/backend/_iluvatar/__init__.py
- src/flag_gems/runtime/backend/_iluvatar/heuristics_config_utils.py
- src/flag_gems/runtime/backend/_iluvatar/ops/__init__.py
- src/flag_gems/runtime/backend/_iluvatar/ops/bmm.py
- src/flag_gems/runtime/backend/_iluvatar/ops/mm.py
- src/flag_gems/runtime/backend/_iluvatar/tune_configs.yaml
- src/flag_gems/runtime/backend/device.py
- tests/test_reduction_ops.py
Other
New Feature
* examples/model_bert_test.py: use cpu reference rather fp64 cuda
* src/flag_gems/ops/upsample_bicubic2d_aa.py: triton 2.1 not support tenary if 
* src/flag_gems/ops/topk.py: triton 2.1 not implement _log2
* src/flag_gems/ops/attention.py: triton 2.1 do not provide default args for prune_configs_by
* tests/accuracy_utils.py: avoid use fp64
* tests/test_reduction_ops.py: no need upcast for int? we meet problem comparing res:  0(int32) with 0.0(float64).
*  src/flag_gems/runtime/backend/_iluvatar: add our backend
I don not use libtuner in mm, since somehow lose sime args, maybe we merge the PR, and then fix the problem
I almost push all the needed fix, except the 
* in libentry.py we use api in triton 2.1 https://github.com/FlagOpen/FlagGems/commit/248785cd66e75dd425bf7351d …
> [Muti backend] add iluvatar backend

- benchmark/test_norm_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/batch_norm.py
- src/flag_gems/runtime/backend/_nvidia/heuristics_config_utils.py
- src/flag_gems/runtime/backend/_nvidia/tune_configs.yaml
- tests/test_norm_ops.py
Operator
New Feature
Implement batch_norm operator
- forward
- backward
- Resolves #258 
- Resolves #315
> [Operator] Add batch_norm

- OperatorList.md
- benchmark/test_reduction_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/argmin.py
- src/flag_gems/runtime/backend/_nvidia/heuristics_config_utils.py
- src/flag_gems/runtime/backend/_nvidia/tune_configs.yaml
- tests/test_reduction_ops.py
Operator, OP Test, Benchmark
New Feature
Support argmin, detail see #318 
Resolves #318 
A100 test result:
Operator: argmin  Performance Test (dtype=torch.float16, mode=cuda, level=comprehensive)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
SUCCESS               0.019456            0.013312               1.462          [torch.Size([1048576])]
SUCCESS               0.010240            0.010240               1.000          [torch.Size([64, 64])]
SUCCESS               0.055296            0.043008               1.286          [torch.Size([4096, 4096])]
SUCCESS               0.055296            0.043008               1.286          [torch.Size([64, 512, …
> add argmin (#318)

- src/flag_gems/runtime/backend/_metax/heuristics_config_utils.py
- src/flag_gems/runtime/backend/_metax/ops/groupnorm.py
- src/flag_gems/runtime/backend/_metax/ops/log_softmax.py
- src/flag_gems/runtime/backend/_metax/tune_configs.yaml
Fix metax backend op bugs
1. Reduce log_softmax private memory usage.
2. Update group_norm to support None type input.
3. Add new op config.
> [Metax] fix metax custom ops

- src/flag_gems/__init__.py
- src/flag_gems/runtime/__init__.py
- src/flag_gems/runtime/backend/README.md
- src/flag_gems/runtime/backend/__init__.py
- src/flag_gems/runtime/backend/_iluvatar/__init__.py
- src/flag_gems/runtime/backend/_iluvatar/ops/__init__.py
- src/flag_gems/runtime/backend/_metax/__init__.py
- src/flag_gems/runtime/backend/_metax/ops/__init__.py
- src/flag_gems/runtime/backend/_nvidia/__init__.py
- src/flag_gems/runtime/backend/_nvidia/fused/__init__.py
- src/flag_gems/runtime/backend/_nvidia/fused/skip_rms_norm.py
- src/flag_gems/runtime/backend/_nvidia/ops/__init__.py
- src/flag_gems/runtime/configloader.py
- src/flag_gems/runtime/error.py
- src/flag_gems/runtime/register.py
Other
New Feature 
1.Support for vendor-customized fused-operators
2.Supports the usage mode of users similar to `flag_gems.op_name`,such as:
```python
import flag_gems
flag_gems.add()
flag_gems.skip_rms_norm()
```
3.Simplify vendor access: after the update, users only need to import operators in the `vendor/ops/__init__.py` directory. for example:
```python
from .add import add
from .gelu import gelu
__all__ = ["add", "gelu"]
```
and vendor only need to provide `vendor_info` and `CUSTOMIZED_UNUSED_OPS` in `vendor/__init__.py`.for example:
```python
from backend_utils import VendorInfoBase  # noqa: E402
vendor_info = VendorInfoBase(
vendor_name="nvidia", device_name="cuda", device_query_cmd="nvidia-smi"
)
CUSTOMIZED_UNUSED_OPS = ("cumsum", "cos", "add")
__all__ = ["*"]
```
> [New Feature] Update muti_backend_framework

- .gitignore
- benchmark/test_select_and_slice_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/gather.py
- src/flag_gems/ops/scatter.py
- src/flag_gems/ops/select_scatter.py
- src/flag_gems/ops/slice_scatter.py
- src/flag_gems/utils/shape_utils.py
- tests/test_reduction_ops.py
Operator
Performance Optimization 
Refactored scatter and gather backward for better performance.  Changes are:
- Use 1d grid of 256 sized blocks, each unrolling 4 times
- Restride inp, index and src to have the same size
- Scatter add/multiply are now using tl atomics 
- Update benchmarks
> Gather bwd

- src/flag_gems/ops/instancenorm.py
Operator
Bug Fix
This change fixes potential out-of-bound access in the following two triton kernels by adding a missing `row_mask` to the `tl.load` operations for `Mean` and `Rstd`. Default values are provided (mean=0.0, rstd=1.0) to handle masked-out elements.
```diff
- mean = tl.load(Mean).to(tl.float32)
- rstd = tl.load(Rstd).to(tl.float32)
+ mean = tl.load(Mean, mask=row_mask, other=0.0).to(tl.float32)
+ rstd = tl.load(Rstd, mask=row_mask, other=1.0).to(tl.float32)
```
```diff
- mean = tl.load(Mean + mid).to(tl.float32)
- rstd = tl.load(Rstd + mid).to(tl.float32)
+ mean = tl.load(Mean + mid, mask=row_mask).to(tl.float32)
+ rstd = tl.load(Rstd + mid, mask=row_mask).to(tl.float32)
```
p.s. A similar issue is found in #414. 
N/A.
N/A
> [Fix InstanceNorm] Fix a memory out-of-bound access

- src/flag_gems/ops/layernorm.py
Operator
Bug Fix
Similar issue to #413. 
This change adds a missing `row_mask` to the `tl.load` operations for `Mean` and `Rstd` to avoid potential out-of-bound access.
```diff
- mean = tl.load(Mean).to(tl.float32)
- rstd = tl.load(Rstd).to(tl.float32)
+ mean = tl.load(Mean, mask=row_mask).to(tl.float32)
+ rstd = tl.load(Rstd, mask=row_mask).to(tl.float32)
```
N/A
N/A
> [Fix LayerNorm] Fix a memory out-of-bound access

- src/flag_gems/ops/gather.py
- src/flag_gems/ops/pad.py
- src/flag_gems/ops/repeat.py
- src/flag_gems/ops/scatter.py
- src/flag_gems/ops/tile.py
Other
Other
Remove NameSpace usage
> Remove NameSpace usage

- src/flag_gems/ops/argmin.py
- src/flag_gems/runtime/backend/_iluvatar/heuristics_config_utils.py
- src/flag_gems/runtime/backend/_iluvatar/tune_configs.yaml
1. The tl.min function will upcast an int16 input tensor to int32 on iluvatar. Therefore, the min_values should be initialized with dtype=int32; otherwise, the Triton IR cannot be generated.
2. add tune config of batchnorm
> [TEST] fix error in argmin UT when dtype=int16

- tests/accuracy_utils.py
- tests/test_blas_ops.py
OP Test
Bug Fix
there exists slight error between result and reference of operator vdot while ref option is set as cpu.
here I upcast reference input to higher precision and specify torch.complex128 as the corresponding data type for torch.cfloat.
> [Test] upcast cfloat to complex128 as reference

- setup.py
Bug Fix
When I tried to install it with pip from Github with `pip install git+https://github.com/FlagOpen/FlagGems.git`, and then use it in my project, it reports an error `FileNotFoundError: [Errno 2] No such file or directory: '**/.venv/lib/python3.10/site-packages/flag_gems/runtime/backend/_nvidia/tune_configs.yaml'`. It's due to the Yaml files are not packaged correctly during building. Now I reset the package searching patterns, and it works. You can try it with `pip install git+https://github.com/sgjzfzzf/FlagGems.git`.
> Fix a Setup error

- benchmark/test_reduction_perf.py
- tests/test_general_reduction_ops.py
Model Test & Benchmark
Other
tl primitives used in quantile don't work on triton2.2. in this pr, relative tests are skipped to serve for weekly report.
> [Bugfix] skip quantile tests on triton lower than 3.0 and cummin benchmark

- src/flag_gems/ops/gather.py
Operator
Re-implementing gather op
**Before：**
```
Operator: gather  Performance Test (dtype=torch.float16, mode=cuda,level=comprehensive)
Status       Torch Latency (ms)    Gems Latency (ms)         Gems Speedup          Torch GBPS            Gems GBPS           Size Detail
-----------------------------------------------------------------------------------------------------------------------------------------
SUCCESS               0.013024            0.011232               1.160               7.548               8.752          [torch.Size([64, 64]), -1, torch.Size([64, 128])]
SUCCESS               0.013184            0.018400               0.717             119.301              85.482          [torch.Size([256, 256]), -1, torch.Size([256, 512])]
SUCCESS …
```
> Re-implementing gather op

- src/flag_gems/utils/libentry.py
Other
Bug Fix
Config construction in libtuner doesn't fit triton version 3.2. In this pr, LibTuner processes different number of arguments according to triton version, and is compatible with version 2.2, 2.3, 3.0, 3.1 and 3.2.
> [Utils] reorganize preload func of libtuner

- src/flag_gems/runtime/backend/_iluvatar/__init__.py
- src/flag_gems/runtime/backend/_iluvatar/ops/__init__.py
- src/flag_gems/runtime/backend/_iluvatar/ops/div.py
- src/flag_gems/runtime/backend/_iluvatar/tune_configs.yaml
- tests/test_binary_pointwise_ops.py
> [Iluvatar] Update Triton version

- src/flag_gems/ops/scatter.py
- src/flag_gems/runtime/backend/_metax/tune_configs.yaml
Operater
Bug Fix
We found that scatter with `heur_block=128 ` will calculate wrong answer, so need to change it to 256 while running in metax backend
> [Metax] fix accuracy error of scatter in metax

- benchmark/test_binary_pointwise_perf.py
- benchmark/test_reduction_perf.py
- benchmark/test_select_and_slice_perf.py
- benchmark/test_special_perf.py
OP Test
op tests
- adjust the method for skipping unsupported ops with musa backend
- Change the device type of tensor in index_put benchmark test for multi-backends
> MTHREADS: adjust method for skipping unsupported ops

- benchmark/test_norm_perf.py
- src/flag_gems/runtime/backend/_kunlunxin/ops/layernorm.py
- tests/test_norm_ops.py
> Add Layernorm Support

- src/flag_gems/fused/gelu_and_mul.py
- tests/test_binary_pointwise_ops.py
> Add gelu and mul grad

- src/flag_gems/fused/silu_and_mul.py
- tests/test_binary_pointwise_ops.py
> Add silu and mul grad

- src/flag_gems/ops/randperm.py
- src/flag_gems/ops/scatter.py
- src/flag_gems/runtime/backend/_iluvatar/__init__.py
- src/flag_gems/runtime/backend/_iluvatar/ops/__init__.py
- src/flag_gems/runtime/backend/_iluvatar/ops/div.py
- src/flag_gems/runtime/backend/_iluvatar/tune_configs.yaml
- tests/test_binary_pointwise_ops.py
For randerm, I think using 'cg' is sufficient instead of 'wt' and it improves readability. I also benchmarked it and found that it does not impact performance, although I initially expected it might provide some benefits.
> [Iluvatar] fix kron scatter randperm quantile

- benchmark/test_tensor_constructor_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/linspace.py
- tests/test_special_ops.py
Operator
New Feature
Add linspace op
```
benchmark/test_tensor_constructor_perf.py 
Operator: linspace  Performance Test (dtype=torch.float16, mode=cuda,level=comprehensive)
Status       Torch Latency (ms)    Gems Latency (ms)         Gems Speedup          Size Detail
-----------------------------------------------------------------------------------------------
SUCCESS               0.007744            0.007424               1.043          {'start': 0, 'end': 65503, 'steps': 11930, 'dtype': torch.float16, 'device': 'cuda'}
SUCCESS               0.007712            0.006176               1.249          {'start': 0, 'end': 4096, 'steps': 3598, 'dtype': torch.float16, 'device': 'cuda'}
SUCCESS               0.006752            0.006528               1.034          {'start': 0, 'end': 65503, …
```
> Add linspace op

- benchmark/test_special_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/contiguous.py
- tests/test_special_ops.py
Operator
New Feature
Add contiguous op
A100
```
Operator: torch.Tensor.contiguous  Performance Test (dtype=torch.float16, mode=cuda,level=comprehensive)
Status       Torch Latency (ms)    Gems Latency (ms)         Gems Speedup          Size Detail
-----------------------------------------------------------------------------------------------
SUCCESS               2.514880            2.362880               1.064          [torch.Size([536870912])]
SUCCESS               0.009504            0.006944               1.369          [torch.Size([32, 64])]
SUCCESS               0.045408            0.033408               1.359          [torch.Size([2048, 4096])]
SUCCESS               0.045632            0.033696               1.354          [torch.Size([32, 512, 512])]
SUCCESS               2.211552 …
```
> Add contiguous op

- benchmark/test_unary_pointwise_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/log.py
- tests/test_unary_pointwise_ops.py
> Add Log Operator

- tests/test_unary_pointwise_ops.py
OP Test
Other
asserting results equal is not appropriate for cpu mode.
this pr sets reference input tensor as higher precision and only requires output tensors to be close.
> [test] relax the accuracy condition of log op

- src/flag_gems/runtime/backend/_kunlunxin/ops/__init__.py
- src/flag_gems/runtime/backend/_kunlunxin/ops/contiguous.py
- src/flag_gems/runtime/backend/_kunlunxin/ops/fill.py
- tests/test_unary_pointwise_ops.py
> [kunlunxin] add contiguous & fill_

- src/flag_gems/utils/libentry.py
[LIBENTRY]
[New Feature]
Append ```k_args``` to support triton 3.3.x
> [LIBENTRY] support triton 3.3.x

- src/flag_gems/ops/addmm.py
- tests/test_blas_ops.py
[ Operator ]
[ Bug Fix ]
The first argument of `torch.addmm` op is the `bias` matrix, the shape of which should be broadcastable with the output shape. But the implementation of `flag_gems.addmm` only takes the row of `bias` into consideration. e.g. When the shape of `bias` is `(m x n)`, the result is incorrect.
> Fix addmm op bug

- benchmark/test_unary_pointwise_perf.py
Benchmark
Bug Fix
musa mis-skipped benchmark of angle on all other devices. this pr fixed it.
> [benchmark] skip angle for musa

- src/flag_gems/ops/gather.py
- src/flag_gems/ops/index_put.py
- src/flag_gems/ops/pad.py
- src/flag_gems/ops/repeat.py
- src/flag_gems/ops/scatter.py
- src/flag_gems/ops/tile.py
- src/flag_gems/utils/code_utils.py
- src/flag_gems/utils/pointwise_dynamic.py
- tests/test_pointwise_dynamic.py
Other
Other
1. use filelock to avoid writing a module per process in PointwiseDynamiccFunction, 
2. add tests for multiprocessing & multithreading
Previously, PointwiseDynamic woule generate module for pointwise functions with the process id as suffix in filename to avoid conflicts in file-writing. It has 2 drawbacks: filenames with pid prevent file reuse between different runs, it generate duplicated files with different names, which is redundant.
> write to tmp file & replace, avoid writing a module per process in PointwiseDynamic

- src/flag_gems/utils/libentry.py
LIBENTRY
Bug Fix
Fix appending ```k_args``` to support triton 3.3.x
Thanks to 芯原 for reporting this issue.
> [LIBENTRY] Fix triton 3.3.x support

- benchmark/performance_utils.py
- benchmark/test_unary_pointwise_perf.py
- src/flag_gems/__init__.py
- src/flag_gems/ops/__init__.py
- src/flag_gems/ops/to.py
- tests/test_unary_pointwise_ops.py
Operator
New Feature
Add to.dtype op
```
benchmark/test_unary_pointwise_perf.py 
Operator: to_dtype  Performance Test (dtype=torch.float16, mode=cuda,level=comprehensive)
Status       Torch Latency (ms)    Gems Latency (ms)         Gems Speedup               TFLOPS          Size Detail
--------------------------------------------------------------------------------------------------------------------
SUCCESS               4.774944            4.700352               1.016               0.228          [torch.Size([1073741824]), torch.float16]
SUCCESS               0.007744            0.007712               1.004               0.001          [torch.Size([64, 64]), torch.float16]
SUCCESS               0.085920            0.086528               0.993               0.194 …
```
> Add to.dtype op

- tests/test_tensor_constructor_ops.py
- tests/test_unary_pointwise_ops.py
OP Test
Bug Fix
Fix test tensor constructor. When testing zeros_like/ones_like/full_like, we should construct inp tensor on device, then to_reference to ref_inp tensor.
Fix pytest.mark.masked_fill_
> [TEST] Fix unit test of tensor constructor and masked_fill_

- src/flag_gems/ops/cumsum.py
- src/flag_gems/utils/__init__.py
- src/flag_gems/utils/triton_driver_helper.py
- src/flag_gems/utils/triton_lang_helper.py
- tests/test_pointwise_dynamic.py
UTILS
New Feature
If ```torch_device_fn.get_device_properties``` is not supported, use ```triton.runtime.driver.active.utils.get_device_properties```
> [UTILS] Change get_device_properties api

- src/flag_gems/ops/scatter.py
- src/flag_gems/ops/select_scatter.py
- src/flag_gems/ops/slice_scatter.py
- src/flag_gems/runtime/backend/_kunlunxin/ops/scatter.py
- src/flag_gems/runtime/backend/_kunlunxin/ops/select_scatter.py
- src/flag_gems/runtime/backend/_kunlunxin/ops/slice_scatter.py
- src/flag_gems/runtime/backend/_kunlunxin/utils/pointwise_dynamic.py
- src/flag_gems/utils/pointwise_dynamic.py
- src/flag_gems/utils/shape_utils.py
Other
Bug Fix
Rever internal overlapping detection to 3-value classification: Yes, No and TooHard. TooHard is okay for torch to assume no internal overlapping.
> Rever internal overlapping detection to a 3-value classification

- src/flag_gems/utils/libentry.py
LibTuner
New Feature
Update default parameters of LibTuner to adapt to versions after Triton 3.1
This makes the autotuner device-agnostic. Instead of having to know about the existence of e.g. do_bench_cudagraph, it can let the callers decide which backend-specific benchmarking function to use.
See discussion in https://github.com/triton-lang/triton/pull/4496
> [LibTuner] Update default parameters of LibTuner

- ctests/CMakeLists.txt
- ctests/test_triton_rope.cpp
- include/flag_gems/operators.h
- lib/CMakeLists.txt
- lib/rotary_embedding.cpp
- src/flag_gems/csrc/cstub.cpp
- src/flag_gems/modules/rotary_embedding.py
- tests/test_special_ops.py
- triton_src/rotary_embedding.py
Operator
New Feature
add c++ wrapper for rope
> 【C++ Wrapper】add c++ wrapper for rope

- benchmark/test_special_perf.py
- src/flag_gems/ops/sort.py
- tests/test_special_ops.py
Operator
New Feature
Implement OneSweep Radix sort, which supports parallel sorting along sorting dimension.
Not implemented features:
- pack status & flag 
- reduce the status to 32-bit(2bits for flag & 30bits for status)
- inplace radix sort for small sorting dimension size
Features that cannot be implemented in triton
- parallell lookback
Since we have not optimize it to triton's extreme, it sorts faster with 4bits per pass than 8bits per pass.
I optimize for large sorting dimension size. The performance for smaller sorting dimension size is bad.
And the overall performance is not good enough, we can leave it for the future.
```text
test_special_perf.py
Operator: sort  Performance Test (dtype=torch.bool, mode=cuda,level=comprehensive)
Status       Torch Latency (ms)    Gems Latency …
```
> add one-sweep radix sort

- src/flag_gems/ops/div.py
- src/flag_gems/ops/silu.py
- src/flag_gems/utils/triton_lang_extension.py
- src/flag_gems/utils/triton_lang_helper.py
> support.tl.extra.shim.dispatch.to.backends

- ctests/CMakeLists.txt
- ctests/test_triton_bmm.cpp
- include/flag_gems/operators.h
- lib/CMakeLists.txt
- lib/bmm.cpp
- src/flag_gems/csrc/cstub.cpp
- triton_src/bmm.py
Operator
New Feature
CPP wrapper packaging for bmm op.
> [AdvancedCompiler]bmm(cpp wrapper)

- src/flag_gems/ops/all.py
- src/flag_gems/ops/amax.py
- src/flag_gems/ops/any.py
- src/flag_gems/ops/max.py
- src/flag_gems/ops/mean.py
- src/flag_gems/ops/min.py
- src/flag_gems/ops/prod.py
- src/flag_gems/ops/sum.py
- src/flag_gems/utils/libentry.py
- tests/test_libentry.py
libtuner
The current libtuner lacks a field representing the code, which may result in enabling outdated cache after modifying the code. To address this issue, this PR has added the md5 value of the source code as the hash key.
add test UT in `test_libbentry.py` 
```
pytest -s /workspace/FlagGems/tests/test_libentry.py::test_hash_generation 
=============================================================== test session starts ================================================================
platform linux -- Python 3.12.3, pytest-8.1.1, pluggy-1.6.0
rootdir: /workspace/FlagGems
configfile: pytest.ini
plugins: anyio-4.9.0, hypothesis-6.130.8, flakefinder-1.1.0, rerunfailures-15.1, shard-0.1.2, xdist-3.6.1, xdoctest-1.0.2, typeguard-4.3.0
collected 1 item …
```
> add hash key for code in libtuner

- src/flag_gems/utils/libentry.py
- tests/test_libentry.py
libtuner hash value
Bug Fix
Now, the method of hash generation is use source code of kernel function. This will result in changes to the subfunction not being reflected in the hash value. 
So, This PR use jitFuntion cache_key instead of source code as hash.
> modify: use jitFuntion cache_key instead of source code as hash

- src/flag_gems/ops/stack.py
```
benchmark/test_tensor_concat_perf.py 
Operator: stack  Performance Test (dtype=torch.float16, mode=cuda,level=comprehensive)
Status       Torch Latency (ms)    Gems Latency (ms)         Gems Speedup          Size Detail
-----------------------------------------------------------------------------------------------
SUCCESS               0.006784            0.005920               1.146          ([[torch.Size([64, 64]), torch.Size([64, 64]), torch.Size([64, 64])]], {'dim': 0})
SUCCESS               0.006688            0.006080               1.100          ([[torch.Size([64, 64]), torch.Size([64, 64]), torch.Size([64, 64])]], {'dim': -1})
SUCCESS               0.007360            0.006432               1.144          ([[torch.Size([256, 256]), torch.Size([256, 256]), torch.Size([256, …
```
> udpate stack

- src/flag_gems/ops/cat.py
```
benchmark/test_tensor_concat_perf.py 
Operator: cat  Performance Test (dtype=torch.float16, mode=cuda,level=comprehensive)
Status       Torch Latency (ms)    Gems Latency (ms)         Gems Speedup          Size Detail
-----------------------------------------------------------------------------------------------
SUCCESS               0.006832            0.005984               1.142          ([[torch.Size([64, 64]), torch.Size([64, 64]), torch.Size([64, 64])]], {'dim': 0})
SUCCESS               0.006656            0.005952               1.118          ([[torch.Size([64, 64]), torch.Size([64, 64]), torch.Size([64, 64])]], {'dim': -1})
SUCCESS               0.007136            0.006464               1.104          ([[torch.Size([256, 256]), torch.Size([256, 256]), torch.Size([256, …
```
> update op of cat

- src/flag_gems/ops/attention.py
- src/flag_gems/patches/patch_vllm_all.py
Operator
Bug Fix
`custom_gems_flash_attention_impl_forwad` will fail if `max_seqlen_q` is a int instead of `torch.Tensor`. This PR adds logic to check whether it's a `torch.Tensor` and if so it will call `item` method, otherwise it will pass the value directly.
Introduced by PR #781.
> fix fatals when 'max_seqlen_q' is int

- src/flag_gems/fused/flash_mla.py
- src/flag_gems/ops/flash_api.py
- tests/test_attention_ops.py
> [Iluvatar] transpose to match actual tensor layout

- src/flag_gems/ops/attention.py
Operator
Bug Fix
`max_seqlen_q` could be `np.int32`, but it only checks whether it's `torch.Tensor` now.
PR #781, #789
> fix fatals when 'max_seqlen_q' is 'numpy.int32'

- src/flag_gems/csrc/cstub.cpp
Operator
Bug Fix
Remove the pybind11 binding for fill and addmm since they have c10::Scalar parameter, while `c10::Scalar` does not have a fully functional type caster. The `load` method of it is a dummy placeholder which raises error.
For more details, please refer to torch/csrc/utils/pybind.cpp
#809
> fix fill op pybind11 binding

- benchmark/attri_util.py
- benchmark/benchmark_for_models.py
- benchmark/conftest.py
- benchmark/core_shapes.yaml
- benchmark/models_shapes/qwen25.yaml
- benchmark/test_attention_perf.py
- benchmark/test_binary_pointwise_perf.py
- benchmark/test_blas_perf.py
- benchmark/test_distribution_perf.py
- benchmark/test_fused_perf.py
- benchmark/test_generic_pointwise_perf.py
- benchmark/test_norm_perf.py
- benchmark/test_reduction_perf.py
- benchmark/test_select_and_slice_perf.py
- benchmark/test_special_perf.py
- benchmark/test_tensor_concat_perf.py
- benchmark/test_tensor_constructor_perf.py
- benchmark/test_unary_pointwise_perf.py
- src/flag_gems/ops/mm.py
- Updated imports in the benchmark directory to use absolute paths for improved clarity and robustness.
- Added a new script `benchmark_for_models.py` to benchmark all operators and shapes involved in a given model.
- Collected and organized part of the Qwen2.5 operator and shape information into `models_shapes/qwen25.yaml`.
- Updated `mm` benchmark logic to include support for `b_column_major` configurations.
> Add model-based benchmarking support and Qwen2.5 op shape config

- benchmark/test_attention_perf.py
- src/flag_gems/runtime/backend/_metax/heuristics_config_utils.py
- tests/test_attention_ops.py
OP Test
other
1. Reduce block size because the size of shared memory in C500 is smaller than A100.
2. Skip op tests that are not supported in C500 now.
> [METAX] modified op config and skip unsupported op tests

- benchmark/attri_util.py
- benchmark/conftest.py
- benchmark/performance_utils.py
Benchmark
New Feature
set new choices 'kernel', 'operator' and 'wrapper' for option mode.
'kernel' mode: get the latency of triton kernel on accelerator
'operator' mode: get the latency of gems operator from end to end on cpu
'wrapper' mode: get the latency of gems operator implemented by python or cpp
> [Benchmark] support profiling wrapper cpu time cost

- benchmark/performance_utils.py
- benchmark/test_attention_perf.py
Benchmark 
Bug Fix 
The bug was import by flash_attn_varlen_func benchmark. 
flash_attn_varlen_func test will try to import vllm, and then all pytest logger config will be changed by unknown reason.
> Fix: logger conflict by import vllm

- docs/ctest_in_flaggems.md
- lib/add.cpp
- lib/argmax.cpp
- lib/contiguous.cpp
- lib/fill.cpp
- lib/max.cpp
- lib/sum.cpp
- lib/zeros.cpp
Other
Other
use `CUstream`
```c++
c10::cuda::CUDAStream stream = c10::cuda::getCurrentCUDAStream();
CUstream  raw_stream = static_cast<CUstream>(stream.stream());
f(raw_stream, grid_x, grid_y, 1, num_warps, num_stages, ...);
```
instead of `c10::cuda::CUDAStream` 
```c++
c10::cuda::CUDAStream stream = c10::cuda::getCurrentCUDAStream();
CUstream  raw_stream = static_cast<CUstream>(stream.stream());
f(stream, grid_x, grid_y, 1, num_warps, num_stages, ...);
```
> use CUstream to launch kernel instead c10::cuda::CUDAStream in cpp warper

- benchmark/test_attention_perf.py
If `flash_attn_varlen_func` is skipped, we need set `os.environ["VLLM_CONFIGURE_LOGGING"] = "0"` again for `test_perf_get_scheduler_metadata`, or `--record log` will not work normally.
> Fix: set VLLM_CONFIGURE_LOGGING=0 to solve logger conflict by import vllm

- benchmark/test_unary_pointwise_perf.py
- src/flag_gems/ops/flash_api.py
- src/flag_gems/ops/flash_kernel.py
- src/flag_gems/runtime/backend/_iluvatar/heuristics_config_utils.py
- tests/test_attention_ops.py
1. Enable performance tests for `sin` and `cos`.
2. Fix flash_attention_varlen: 1)  compress the last two dimensions for Iluvatar to ensure correct stride handling for async-cp like https://github.com/FlagOpen/FlagGems/pull/783 . 2) refactor to remove unnecessary convert_layout. On Iluvatar, this acts as a workaround to fix an accuracy issue.
On all vendors, this change is expected to improve performance.
3. fix `test_sdpa_legacy`: Iluvatar SDPA CPU backend has known issues, use math backend instead.
4. fix `test_flash_fwd_nonsquare_qk` and `test_flash_fwd_swa`: CUDA FlashAttention on Iluvatar uses a different optimized implementation, which causes LSE to differ from original implementation on math.
5. `test_flash_fwd_dropout`: Verified it passes on NV A100 with Triton, so the test is …
> [Iluvatar] fix sin/cos, FA

- src/flag_gems/fused/flash_mla.py
- src/flag_gems/ops/get_scheduler_metadata.py
Operator 
Refactor 
Some vendors do not support explicit calls to torch.cuda. Use torch_device_fn to replace torch.cuda in order to reduce cases of backend-specific custom operators.
> [Refactor]: Replace direct calls to torch.cuda with torch_device_fn
